/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

using FairyGUI;
using FairyGUI.Utils;

namespace BigMap
{
    public partial class UI_ChapterPanel2 : GComponent
    {
        public GLoader walkMap;
        public UI_MapBg mapbg;
        public GLoader3D ShuiBo1;
        public GLoader3D ShuiBo2;
        public GLoader3D ShuiBo3;
        public GLoader3D ShuiBo4;
        public GLoader3D ShuiBo5;
        public GLoader3D ShuiBo6;
        public UI_stageItem stage1;
        public UI_stageItem stage2;
        public UI_stageItem stage3;
        public UI_stageItem stage4;
        public UI_stageItem stage5;
        public UI_stageItem stage6;
        public UI_stageItem stage7;
        public UI_stageItem stage8;
        public UI_stageItem stage9;
        public UI_stageItem stage10;
        public UI_stageItem stage11;
        public UI_stageItem stage12;
        public UI_stageItem stage13;
        public UI_stageItem stage14;
        public UI_stageItem stage15;
        public UI_stageItem stage16;
        public UI_stageItem stage17;
        public UI_stageItem stage18;
        public UI_stageItem stage19;
        public UI_stageItem stage20;
        public UI_stageItem stageEvent1;
        public UI_stageItem stageEvent2;
        public UI_stageItem stageEvent3;
        public UI_stageItem stageEvent4;
        public UI_stageItem stageEvent5;
        public GLoader3D JZ1;
        public GLoader3D JZ2;
        public GLoader3D JZ3;
        public GLoader3D JZ4;
        public GLoader3D JZ5;
        public GLoader3D JZ6;
        public GLoader3D JZ7;
        public GLoader3D YC9;
        public GLoader3D YC5;
        public GLoader3D JZ10;
        public GLoader3D JZ11;
        public GLoader3D huo1;
        public GLoader3D huo2;
        public GLoader stageNextOld;
        public UI_stageItem stageNext;
        public GLoader3D spineStageNext;
        public GLoader posNext;
        public GLoader pos1;
        public GLoader pos2;
        public GLoader pos3;
        public GLoader pos4;
        public GLoader pos5;
        public GLoader pos6;
        public GLoader pos7;
        public GLoader pos8;
        public GLoader pos9;
        public GLoader pos10;
        public GLoader pos11;
        public GLoader pos12;
        public GLoader pos13;
        public GLoader pos14;
        public GLoader pos15;
        public GLoader pos16;
        public GLoader pos17;
        public GLoader pos18;
        public GLoader pos19;
        public GLoader pos20;
        public GLoader posEvent1;
        public GLoader posEvent2;
        public GLoader posEvent3;
        public GLoader posEvent4;
        public GLoader posEvent5;
        public GLoader fishingPos1;
        public GLoader fishingPos2;
        public GLoader fishingPos3;
        public GLoader fishingPos4;
        public GLoader fishingPos5;
        public GLoader fishingPos6;
        public GLoader fishingDirection1;
        public GLoader fishingDirection2;
        public GLoader fishingDirection3;
        public GLoader fishingDirection4;
        public GLoader fishingDirection5;
        public GLoader fishingDirection6;
        public GLoader posLast;
        public GLoader btnLastChapterOld;
        public UI_stageItem btnLastChapter;
        public GLoader3D spineLastChapter;
        public GLoader3D feng1;
        public GLoader3D feng2;
        public GLoader3D feng3;
        public const string URL = "ui://pdufy3keusf5ii4";

        public static UI_ChapterPanel2 CreateInstance()
        {
            return (UI_ChapterPanel2)UIPackage.CreateObject("BigMap", "ChapterPanel2");
        }

        public override void ConstructFromXML(XML xml)
        {
            base.ConstructFromXML(xml);

            walkMap = (GLoader)GetChild("walkMap");
            mapbg = (UI_MapBg)GetChild("mapbg");
            ShuiBo1 = (GLoader3D)GetChild("ShuiBo1");
            ShuiBo2 = (GLoader3D)GetChild("ShuiBo2");
            ShuiBo3 = (GLoader3D)GetChild("ShuiBo3");
            ShuiBo4 = (GLoader3D)GetChild("ShuiBo4");
            ShuiBo5 = (GLoader3D)GetChild("ShuiBo5");
            ShuiBo6 = (GLoader3D)GetChild("ShuiBo6");
            stage1 = (UI_stageItem)GetChild("stage1");
            stage2 = (UI_stageItem)GetChild("stage2");
            stage3 = (UI_stageItem)GetChild("stage3");
            stage4 = (UI_stageItem)GetChild("stage4");
            stage5 = (UI_stageItem)GetChild("stage5");
            stage6 = (UI_stageItem)GetChild("stage6");
            stage7 = (UI_stageItem)GetChild("stage7");
            stage8 = (UI_stageItem)GetChild("stage8");
            stage9 = (UI_stageItem)GetChild("stage9");
            stage10 = (UI_stageItem)GetChild("stage10");
            stage11 = (UI_stageItem)GetChild("stage11");
            stage12 = (UI_stageItem)GetChild("stage12");
            stage13 = (UI_stageItem)GetChild("stage13");
            stage14 = (UI_stageItem)GetChild("stage14");
            stage15 = (UI_stageItem)GetChild("stage15");
            stage16 = (UI_stageItem)GetChild("stage16");
            stage17 = (UI_stageItem)GetChild("stage17");
            stage18 = (UI_stageItem)GetChild("stage18");
            stage19 = (UI_stageItem)GetChild("stage19");
            stage20 = (UI_stageItem)GetChild("stage20");
            stageEvent1 = (UI_stageItem)GetChild("stageEvent1");
            stageEvent2 = (UI_stageItem)GetChild("stageEvent2");
            stageEvent3 = (UI_stageItem)GetChild("stageEvent3");
            stageEvent4 = (UI_stageItem)GetChild("stageEvent4");
            stageEvent5 = (UI_stageItem)GetChild("stageEvent5");
            JZ1 = (GLoader3D)GetChild("JZ1");
            JZ2 = (GLoader3D)GetChild("JZ2");
            JZ3 = (GLoader3D)GetChild("JZ3");
            JZ4 = (GLoader3D)GetChild("JZ4");
            JZ5 = (GLoader3D)GetChild("JZ5");
            JZ6 = (GLoader3D)GetChild("JZ6");
            JZ7 = (GLoader3D)GetChild("JZ7");
            YC9 = (GLoader3D)GetChild("YC9");
            YC5 = (GLoader3D)GetChild("YC5");
            JZ10 = (GLoader3D)GetChild("JZ10");
            JZ11 = (GLoader3D)GetChild("JZ11");
            huo1 = (GLoader3D)GetChild("huo1");
            huo2 = (GLoader3D)GetChild("huo2");
            stageNextOld = (GLoader)GetChild("stageNextOld");
            stageNext = (UI_stageItem)GetChild("stageNext");
            spineStageNext = (GLoader3D)GetChild("spineStageNext");
            posNext = (GLoader)GetChild("posNext");
            pos1 = (GLoader)GetChild("pos1");
            pos2 = (GLoader)GetChild("pos2");
            pos3 = (GLoader)GetChild("pos3");
            pos4 = (GLoader)GetChild("pos4");
            pos5 = (GLoader)GetChild("pos5");
            pos6 = (GLoader)GetChild("pos6");
            pos7 = (GLoader)GetChild("pos7");
            pos8 = (GLoader)GetChild("pos8");
            pos9 = (GLoader)GetChild("pos9");
            pos10 = (GLoader)GetChild("pos10");
            pos11 = (GLoader)GetChild("pos11");
            pos12 = (GLoader)GetChild("pos12");
            pos13 = (GLoader)GetChild("pos13");
            pos14 = (GLoader)GetChild("pos14");
            pos15 = (GLoader)GetChild("pos15");
            pos16 = (GLoader)GetChild("pos16");
            pos17 = (GLoader)GetChild("pos17");
            pos18 = (GLoader)GetChild("pos18");
            pos19 = (GLoader)GetChild("pos19");
            pos20 = (GLoader)GetChild("pos20");
            posEvent1 = (GLoader)GetChild("posEvent1");
            posEvent2 = (GLoader)GetChild("posEvent2");
            posEvent3 = (GLoader)GetChild("posEvent3");
            posEvent4 = (GLoader)GetChild("posEvent4");
            posEvent5 = (GLoader)GetChild("posEvent5");
            fishingPos1 = (GLoader)GetChild("fishingPos1");
            fishingPos2 = (GLoader)GetChild("fishingPos2");
            fishingPos3 = (GLoader)GetChild("fishingPos3");
            fishingPos4 = (GLoader)GetChild("fishingPos4");
            fishingPos5 = (GLoader)GetChild("fishingPos5");
            fishingPos6 = (GLoader)GetChild("fishingPos6");
            fishingDirection1 = (GLoader)GetChild("fishingDirection1");
            fishingDirection2 = (GLoader)GetChild("fishingDirection2");
            fishingDirection3 = (GLoader)GetChild("fishingDirection3");
            fishingDirection4 = (GLoader)GetChild("fishingDirection4");
            fishingDirection5 = (GLoader)GetChild("fishingDirection5");
            fishingDirection6 = (GLoader)GetChild("fishingDirection6");
            posLast = (GLoader)GetChild("posLast");
            btnLastChapterOld = (GLoader)GetChild("btnLastChapterOld");
            btnLastChapter = (UI_stageItem)GetChild("btnLastChapter");
            spineLastChapter = (GLoader3D)GetChild("spineLastChapter");
            feng1 = (GLoader3D)GetChild("feng1");
            feng2 = (GLoader3D)GetChild("feng2");
            feng3 = (GLoader3D)GetChild("feng3");
        }
    }
}