// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace msg {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class UnlockFunction {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_msg_PlayerUnlockFunction_PC__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::msg.PlayerUnlockFunction_PC, global::msg.PlayerUnlockFunction_PC.Builder> internal__static_msg_PlayerUnlockFunction_PC__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static UnlockFunction() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRVbmxvY2tGdW5jdGlvbi5wcm90bxIDbXNnGg1FcnJDb2RlLnByb3RvGgpF", 
            "bnVtLnByb3RvGgxDb21tb24ucHJvdG8iRQoXUGxheWVyVW5sb2NrRnVuY3Rp", 
            "b25fUEMSKgoPdW5sb2NrX2Z1bmN0aW9uGAEgAygLMhEubXNnLkZ1bmN0aW9u", 
            "SW5mbyqBAQoUZVVubG9ja0Z1bmNDb25kaXRpb24SIgoeZVVubG9ja0Z1bmND", 
            "b25kaXRpb25fSGVyb0xldmVsEAESIQodZVVubG9ja0Z1bmNDb25kaXRpb25f", 
            "TWFpblRhc2sQAhIiCh5lVW5sb2NrRnVuY0NvbmRpdGlvbl9QYXNzU3RhZ2UQ", 
            "AyreEgoPZVVubG9ja0Z1bmN0aW9uEh4KGmVVbmxvY2tGdW5jdGlvbl9QZXJz", 
            "b25JbmZvEGQSHQoYZVVubG9ja0Z1bmN0aW9uX01haW5UYXNrEMgBEiAKG2VV", 
            "bmxvY2tGdW5jdGlvbl9SaW5nTGV2ZWxVcBCsAhIdChhlVW5sb2NrRnVuY3Rp", 
            "b25fUmluZ0luZm8QkAMSHgoZZVVubG9ja0Z1bmN0aW9uX1JlZFBvaW50cxD0", 
            "AxIaChVlVW5sb2NrRnVuY3Rpb25fR3VpZGUQ2AQSHQoYZVVubG9ja0Z1bmN0", 
            "aW9uX1Bhc3NQb3J0ELwFEhkKFGVVbmxvY2tGdW5jdGlvbl9NYWxsEL0FEh0K", 
            "GGVVbmxvY2tGdW5jdGlvbl9QYWNrU2hvcBC+BRIeChllVW5sb2NrRnVuY3Rp", 
            "b25fTG9naW5QYWNrEL8FEh4KGWVVbmxvY2tGdW5jdGlvbl9Xb3JsZENoYXQQ", 
            "oAYSIwoeZVVubG9ja0Z1bmN0aW9uX0NvbGxlY3Rpb25Cb29rEMwIEhkKFGVV", 
            "bmxvY2tGdW5jdGlvbl9NYWlsELAJEioKJWVVbmxvY2tGdW5jdGlvbl9GaXJz", 
            "dFJlY2hhcmdlR2lmdFBhY2sQlAoSHwoaZVVubG9ja0Z1bmN0aW9uX05vb2JT", 
            "aWduSW4Q+AoSHgoZZVVubG9ja0Z1bmN0aW9uX0RhaWx5VGFzaxDcCxIeChll", 
            "VW5sb2NrRnVuY3Rpb25fSWRsZUF3YXJkEMAMEh0KGGVVbmxvY2tGdW5jdGlv", 
            "bl9FcXVpcEJveBCkDRIhChxlVW5sb2NrRnVuY3Rpb25fQXV0b0dlbkVxdWlw", 
            "EKUNEh4KGWVVbmxvY2tGdW5jdGlvbl9Mb3JlRXF1aXAQpg0SIgodZVVubG9j", 
            "a0Z1bmN0aW9uX0FydGlmYWN0RXF1aXAQpw0SHwoaZVVubG9ja0Z1bmN0aW9u", 
            "X0Z1bmN0aW9uVUkQiA4SIAobZVVubG9ja0Z1bmN0aW9uX0hlcm9MZXZlbFVw", 
            "EIkOEh4KGWVVbmxvY2tGdW5jdGlvbl9IZXJvQnJlYWsQig4SJQogZVVubG9j", 
            "a0Z1bmN0aW9uX0hlcm9Ta2lsbExldmVsVXAQiw4SHwoaZVVubG9ja0Z1bmN0", 
            "aW9uX0hlcm9UYWxlbnQQjA4SIAobZVVubG9ja0Z1bmN0aW9uX0hlcm9DbGFz", 
            "c2ljEI0OEh0KGGVVbmxvY2tGdW5jdGlvbl9Ib2x5SXRlbRCODhIaChVlVW5s", 
            "b2NrRnVuY3Rpb25fU2tpbGwQ7A4SHwoaZVVubG9ja0Z1bmN0aW9uX1NraWxs", 
            "U2xvdDEQ7Q4SHwoaZVVubG9ja0Z1bmN0aW9uX1NraWxsU2xvdDIQ7g4SHwoa", 
            "ZVVubG9ja0Z1bmN0aW9uX1NraWxsU2xvdDMQ7w4SHwoaZVVubG9ja0Z1bmN0", 
            "aW9uX1NraWxsU2xvdDQQ8A4SHwoaZVVubG9ja0Z1bmN0aW9uX1NraWxsU2xv", 
            "dDUQ8Q4SGAoTZVVubG9ja0Z1bmN0aW9uX1BldBDQDxIdChhlVW5sb2NrRnVu", 
            "Y3Rpb25fUGV0U2xvdDEQ0Q8SHQoYZVVubG9ja0Z1bmN0aW9uX1BldFNsb3Qy", 
            "ENIPEh0KGGVVbmxvY2tGdW5jdGlvbl9QZXRTbG90MxDTDxIdChhlVW5sb2Nr", 
            "RnVuY3Rpb25fUGV0TGV2ZWwQ1A8SJAofZVVubG9ja0Z1bmN0aW9uX1BldFNr", 
            "aWxsTGV2ZWxVcBDVDxIeChllVW5sb2NrRnVuY3Rpb25fUGV0VGFsZW50ENYP", 
            "EiEKHGVVbmxvY2tGdW5jdGlvbl9QZXRTa2lsbEJvb2sQ1w8SHgoZZVVubG9j", 
            "a0Z1bmN0aW9uX0hlcm9Mb3R0bxC0EBIZChRlVW5sb2NrRnVuY3Rpb25fQ29w", 
            "eRCYERIdChhlVW5sb2NrRnVuY3Rpb25fR29sZENvcHkQmRESHgoZZVVubG9j", 
            "a0Z1bmN0aW9uX0VxdWlwQ29weRCaERIgChtlVW5sb2NrRnVuY3Rpb25fRGlh", 
            "bW9uZENvcHkQmxESIAobZVVubG9ja0Z1bmN0aW9uX0hlcm9FeHBDb3B5EJwR", 
            "EiEKHGVVbmxvY2tGdW5jdGlvbl9QZXRTdHVmZkNvcHkQnRESJQogZVVubG9j", 
            "a0Z1bmN0aW9uX1BldFNraWxsQm9va0NvcHkQnhESIQocZVVubG9ja0Z1bmN0", 
            "aW9uX0FydGlmYWN0Q29weRCfERIhChxlVW5sb2NrRnVuY3Rpb25fSG9seUl0", 
            "ZW1Db3B5EKAREh0KGGVVbmxvY2tGdW5jdGlvbl9Ib21lVG93bhD8ERIZChRl", 
            "VW5sb2NrRnVuY3Rpb25fTWluZRD9ERIhChxlVW5sb2NrRnVuY3Rpb25fRmlu", 
            "YWxGYWN0b3J5EP4REiAKG2VVbmxvY2tGdW5jdGlvbl9Gb29kRmFjdG9yeRD/", 
            "ERIjCh5lVW5sb2NrRnVuY3Rpb25fVHJhaW5pbmdHcm91bmQQgBISHgoZZVVu", 
            "bG9ja0Z1bmN0aW9uX1JlcHJvZHVjZRCBEhIZChRlVW5sb2NrRnVuY3Rpb25f", 
            "Q2FtcBCCEhIjCh5lVW5sb2NrRnVuY3Rpb25fRXZlbnRSYW5kb21Cb3gQ4BIS", 
            "IwoeZVVubG9ja0Z1bmN0aW9uX0V2ZW50UnVpbnNCdWZmEOESEiEKHGVVbmxv", 
            "Y2tGdW5jdGlvbl9FdmVudE5wY1Rhc2sQ4hISJgohZVVubG9ja0Z1bmN0aW9u", 
            "X0V2ZW50U3RhZ2VEcm9wUGV0EOMSEikKJGVVbmxvY2tGdW5jdGlvbl9FdmVu", 
            "dE5leHRDaGFwdGVyQm9zcxDkEhInCiJlVW5sb2NrRnVuY3Rpb25fRXZlbnRS", 
            "YW5kb21EaWFtb25kEOUSEiQKH2VVbmxvY2tGdW5jdGlvbl9FdmVudFJhbmRv", 
            "bUdvbGQQ5hISJAofZVVubG9ja0Z1bmN0aW9uX0V2ZW50UmFuZG9tRXVpcBDn", 
            "EhIhChxlVW5sb2NrRnVuY3Rpb25fRXZlbnRGaXNoaW5nEOgSEi4KKWVVbmxv", 
            "Y2tGdW5jdGlvbl9FdmVudEFkdmVudHVyZUJ1c2luZXNzTWFuEOkSEiAKG2VV", 
            "bmxvY2tGdW5jdGlvbl9HbG9iYWxGaXJzdBDEExIgChtlVW5sb2NrRnVuY3Rp", 
          "b25fQWNoaWV2ZW1lbnQQqBQ="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_msg_PlayerUnlockFunction_PC__Descriptor = Descriptor.MessageTypes[0];
        internal__static_msg_PlayerUnlockFunction_PC__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::msg.PlayerUnlockFunction_PC, global::msg.PlayerUnlockFunction_PC.Builder>(internal__static_msg_PlayerUnlockFunction_PC__Descriptor,
                new string[] { "UnlockFunction", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::msg.ErrCode.Descriptor, 
          global::msg.Enum.Descriptor, 
          global::msg.Common.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum eUnlockFuncCondition {
    eUnlockFuncCondition_HeroLevel = 1,
    eUnlockFuncCondition_MainTask = 2,
    eUnlockFuncCondition_PassStage = 3,
  }
  
  public enum eUnlockFunction {
    eUnlockFunction_PersonInfo = 100,
    eUnlockFunction_MainTask = 200,
    eUnlockFunction_RingLevelUp = 300,
    eUnlockFunction_RingInfo = 400,
    eUnlockFunction_RedPoints = 500,
    eUnlockFunction_Guide = 600,
    eUnlockFunction_PassPort = 700,
    eUnlockFunction_Mall = 701,
    eUnlockFunction_PackShop = 702,
    eUnlockFunction_LoginPack = 703,
    eUnlockFunction_WorldChat = 800,
    eUnlockFunction_CollectionBook = 1100,
    eUnlockFunction_Mail = 1200,
    eUnlockFunction_FirstRechargeGiftPack = 1300,
    eUnlockFunction_NoobSignIn = 1400,
    eUnlockFunction_DailyTask = 1500,
    eUnlockFunction_IdleAward = 1600,
    eUnlockFunction_EquipBox = 1700,
    eUnlockFunction_AutoGenEquip = 1701,
    eUnlockFunction_LoreEquip = 1702,
    eUnlockFunction_ArtifactEquip = 1703,
    eUnlockFunction_FunctionUI = 1800,
    eUnlockFunction_HeroLevelUp = 1801,
    eUnlockFunction_HeroBreak = 1802,
    eUnlockFunction_HeroSkillLevelUp = 1803,
    eUnlockFunction_HeroTalent = 1804,
    eUnlockFunction_HeroClassic = 1805,
    eUnlockFunction_HolyItem = 1806,
    eUnlockFunction_Skill = 1900,
    eUnlockFunction_SkillSlot1 = 1901,
    eUnlockFunction_SkillSlot2 = 1902,
    eUnlockFunction_SkillSlot3 = 1903,
    eUnlockFunction_SkillSlot4 = 1904,
    eUnlockFunction_SkillSlot5 = 1905,
    eUnlockFunction_Pet = 2000,
    eUnlockFunction_PetSlot1 = 2001,
    eUnlockFunction_PetSlot2 = 2002,
    eUnlockFunction_PetSlot3 = 2003,
    eUnlockFunction_PetLevel = 2004,
    eUnlockFunction_PetSkillLevelUp = 2005,
    eUnlockFunction_PetTalent = 2006,
    eUnlockFunction_PetSkillBook = 2007,
    eUnlockFunction_HeroLotto = 2100,
    eUnlockFunction_Copy = 2200,
    eUnlockFunction_GoldCopy = 2201,
    eUnlockFunction_EquipCopy = 2202,
    eUnlockFunction_DiamondCopy = 2203,
    eUnlockFunction_HeroExpCopy = 2204,
    eUnlockFunction_PetStuffCopy = 2205,
    eUnlockFunction_PetSkillBookCopy = 2206,
    eUnlockFunction_ArtifactCopy = 2207,
    eUnlockFunction_HolyItemCopy = 2208,
    eUnlockFunction_HomeTown = 2300,
    eUnlockFunction_Mine = 2301,
    eUnlockFunction_FinalFactory = 2302,
    eUnlockFunction_FoodFactory = 2303,
    eUnlockFunction_TrainingGround = 2304,
    eUnlockFunction_Reproduce = 2305,
    eUnlockFunction_Camp = 2306,
    eUnlockFunction_EventRandomBox = 2400,
    eUnlockFunction_EventRuinsBuff = 2401,
    eUnlockFunction_EventNpcTask = 2402,
    eUnlockFunction_EventStageDropPet = 2403,
    eUnlockFunction_EventNextChapterBoss = 2404,
    eUnlockFunction_EventRandomDiamond = 2405,
    eUnlockFunction_EventRandomGold = 2406,
    eUnlockFunction_EventRandomEuip = 2407,
    eUnlockFunction_EventFishing = 2408,
    eUnlockFunction_EventAdventureBusinessMan = 2409,
    eUnlockFunction_GlobalFirst = 2500,
    eUnlockFunction_Achievement = 2600,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PlayerUnlockFunction_PC : pb::GeneratedMessage<PlayerUnlockFunction_PC, PlayerUnlockFunction_PC.Builder> {
    private PlayerUnlockFunction_PC() { }
    private static readonly PlayerUnlockFunction_PC defaultInstance = new PlayerUnlockFunction_PC().MakeReadOnly();
    private static readonly string[] _playerUnlockFunctionPCFieldNames = new string[] { "unlock_function" };
    private static readonly uint[] _playerUnlockFunctionPCFieldTags = new uint[] { 10 };
    public static PlayerUnlockFunction_PC DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override PlayerUnlockFunction_PC DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override PlayerUnlockFunction_PC ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::msg.UnlockFunction.internal__static_msg_PlayerUnlockFunction_PC__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<PlayerUnlockFunction_PC, PlayerUnlockFunction_PC.Builder> InternalFieldAccessors {
      get { return global::msg.UnlockFunction.internal__static_msg_PlayerUnlockFunction_PC__FieldAccessorTable; }
    }
    
    public const int UnlockFunctionFieldNumber = 1;
    private pbc::PopsicleList<global::msg.FunctionInfo> unlockFunction_ = new pbc::PopsicleList<global::msg.FunctionInfo>();
    public scg::IList<global::msg.FunctionInfo> UnlockFunctionList {
      get { return unlockFunction_; }
    }
    public int UnlockFunctionCount {
      get { return unlockFunction_.Count; }
    }
    public global::msg.FunctionInfo GetUnlockFunction(int index) {
      return unlockFunction_[index];
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _playerUnlockFunctionPCFieldNames;
      if (unlockFunction_.Count > 0) {
        output.WriteMessageArray(1, field_names[0], unlockFunction_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      foreach (global::msg.FunctionInfo element in UnlockFunctionList) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static PlayerUnlockFunction_PC ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static PlayerUnlockFunction_PC ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private PlayerUnlockFunction_PC MakeReadOnly() {
      unlockFunction_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(PlayerUnlockFunction_PC prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<PlayerUnlockFunction_PC, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(PlayerUnlockFunction_PC cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private PlayerUnlockFunction_PC result;
      
      private PlayerUnlockFunction_PC PrepareBuilder() {
        if (resultIsReadOnly) {
          PlayerUnlockFunction_PC original = result;
          result = new PlayerUnlockFunction_PC();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override PlayerUnlockFunction_PC MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::msg.PlayerUnlockFunction_PC.Descriptor; }
      }
      
      public override PlayerUnlockFunction_PC DefaultInstanceForType {
        get { return global::msg.PlayerUnlockFunction_PC.DefaultInstance; }
      }
      
      public override PlayerUnlockFunction_PC BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is PlayerUnlockFunction_PC) {
          return MergeFrom((PlayerUnlockFunction_PC) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(PlayerUnlockFunction_PC other) {
        if (other == global::msg.PlayerUnlockFunction_PC.DefaultInstance) return this;
        PrepareBuilder();
        if (other.unlockFunction_.Count != 0) {
          result.unlockFunction_.Add(other.unlockFunction_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_playerUnlockFunctionPCFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _playerUnlockFunctionPCFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadMessageArray(tag, field_name, result.unlockFunction_, global::msg.FunctionInfo.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<global::msg.FunctionInfo> UnlockFunctionList {
        get { return PrepareBuilder().unlockFunction_; }
      }
      public int UnlockFunctionCount {
        get { return result.UnlockFunctionCount; }
      }
      public global::msg.FunctionInfo GetUnlockFunction(int index) {
        return result.GetUnlockFunction(index);
      }
      public Builder SetUnlockFunction(int index, global::msg.FunctionInfo value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.unlockFunction_[index] = value;
        return this;
      }
      public Builder SetUnlockFunction(int index, global::msg.FunctionInfo.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.unlockFunction_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddUnlockFunction(global::msg.FunctionInfo value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.unlockFunction_.Add(value);
        return this;
      }
      public Builder AddUnlockFunction(global::msg.FunctionInfo.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.unlockFunction_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeUnlockFunction(scg::IEnumerable<global::msg.FunctionInfo> values) {
        PrepareBuilder();
        result.unlockFunction_.Add(values);
        return this;
      }
      public Builder ClearUnlockFunction() {
        PrepareBuilder();
        result.unlockFunction_.Clear();
        return this;
      }
    }
    static PlayerUnlockFunction_PC() {
      object.ReferenceEquals(global::msg.UnlockFunction.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
