// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace msg {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class Vip {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static Vip() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglWaXAucHJvdG8SA21zZxoNRXJyQ29kZS5wcm90bxoKRW51bS5wcm90bxoM", 
          "Q29tbW9uLnByb3Rv"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::msg.ErrCode.Descriptor, 
          global::msg.Enum.Descriptor, 
          global::msg.Common.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
}

#endregion Designer generated code
