// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigContinuousSaveUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigContinuousSaveUnit.proto</summary>
  public static partial class ConfigContinuousSaveUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigContinuousSaveUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigContinuousSaveUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Db25maWdDb250aW51b3VzU2F2ZVVuaXQucHJvdG8SBkNvbmZpZyKFAQoY",
            "Q29uZmlnQ29udGludW91c1NhdmVVbml0EgoKAklkGAEgASgFEhAKCE5hbWVO",
            "b3RlGAIgASgJEgwKBE5hbWUYAyABKAkSEQoJTmFtZVBhcmFtGAQgASgJEgsK",
            "A0RheRgFIAEoBRIOCgZJdGVtSWQYBiABKAkSDQoFTm90ZXMYByABKAliBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigContinuousSaveUnit), global::Config.ConfigContinuousSaveUnit.Parser, new[]{ "Id", "NameNote", "Name", "NameParam", "Day", "ItemId", "Notes" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigContinuousSaveUnit : pb::IMessage<ConfigContinuousSaveUnit> {
    private static readonly pb::MessageParser<ConfigContinuousSaveUnit> _parser = new pb::MessageParser<ConfigContinuousSaveUnit>(() => new ConfigContinuousSaveUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigContinuousSaveUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigContinuousSaveUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigContinuousSaveUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigContinuousSaveUnit(ConfigContinuousSaveUnit other) : this() {
      id_ = other.id_;
      nameNote_ = other.nameNote_;
      name_ = other.name_;
      nameParam_ = other.nameParam_;
      day_ = other.day_;
      itemId_ = other.itemId_;
      notes_ = other.notes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigContinuousSaveUnit Clone() {
      return new ConfigContinuousSaveUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "NameNote" field.</summary>
    public const int NameNoteFieldNumber = 2;
    private string nameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameNote {
      get { return nameNote_; }
      set {
        nameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NameParam" field.</summary>
    public const int NameParamFieldNumber = 4;
    private string nameParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameParam {
      get { return nameParam_; }
      set {
        nameParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Day" field.</summary>
    public const int DayFieldNumber = 5;
    private int day_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Day {
      get { return day_; }
      set {
        day_ = value;
      }
    }

    /// <summary>Field number for the "ItemId" field.</summary>
    public const int ItemIdFieldNumber = 6;
    private string itemId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemId {
      get { return itemId_; }
      set {
        itemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Notes" field.</summary>
    public const int NotesFieldNumber = 7;
    private string notes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Notes {
      get { return notes_; }
      set {
        notes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigContinuousSaveUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigContinuousSaveUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NameNote != other.NameNote) return false;
      if (Name != other.Name) return false;
      if (NameParam != other.NameParam) return false;
      if (Day != other.Day) return false;
      if (ItemId != other.ItemId) return false;
      if (Notes != other.Notes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (NameNote.Length != 0) hash ^= NameNote.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (NameParam.Length != 0) hash ^= NameParam.GetHashCode();
      if (Day != 0) hash ^= Day.GetHashCode();
      if (ItemId.Length != 0) hash ^= ItemId.GetHashCode();
      if (Notes.Length != 0) hash ^= Notes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (NameNote.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameNote);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameParam.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameParam);
      }
      if (Day != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Day);
      }
      if (ItemId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ItemId);
      }
      if (Notes.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Notes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (NameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNote);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (NameParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameParam);
      }
      if (Day != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Day);
      }
      if (ItemId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemId);
      }
      if (Notes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Notes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigContinuousSaveUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.NameNote.Length != 0) {
        NameNote = other.NameNote;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.NameParam.Length != 0) {
        NameParam = other.NameParam;
      }
      if (other.Day != 0) {
        Day = other.Day;
      }
      if (other.ItemId.Length != 0) {
        ItemId = other.ItemId;
      }
      if (other.Notes.Length != 0) {
        Notes = other.Notes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            NameNote = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameParam = input.ReadString();
            break;
          }
          case 40: {
            Day = input.ReadInt32();
            break;
          }
          case 50: {
            ItemId = input.ReadString();
            break;
          }
          case 58: {
            Notes = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
