// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigAptitudeUnlock.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using Engine;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigAptitudeUnlock.proto</summary>
  public static partial class ConfigAptitudeUnlockReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigAptitudeUnlock.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigAptitudeUnlockReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDb25maWdBcHRpdHVkZVVubG9jay5wcm90bxIGQ29uZmlnGh5Db25maWdB",
            "cHRpdHVkZVVubG9ja1VuaXQucHJvdG8iRgoUQ29uZmlnQXB0aXR1ZGVVbmxv",
            "Y2sSLgoEZGF0YRgBIAMoCzIgLkNvbmZpZy5Db25maWdBcHRpdHVkZVVubG9j",
            "a1VuaXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Config.ConfigAptitudeUnlockUnitReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigAptitudeUnlock), global::Config.ConfigAptitudeUnlock.Parser, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigAptitudeUnlock : pb::IMessage<ConfigAptitudeUnlock>, EngineBase.IConfigBase {
    
    public static ConfigAptitudeUnlock GetNewConfig(byte[] bytes) { 
        if (bytes == null) return null;
        ConfigAptitudeUnlock config = (ConfigAptitudeUnlock)ConfigAptitudeUnlock.Descriptor.Parser.ParseFrom(bytes);
        return config;
    }
    public ConfigAptitudeUnlockUnit Get(int key) {
        if (key >= 0 && key < this.Data.Count)
            return this.Data[key];
        return null;
    }
    public scg::ICollection<int> Keys {
        get {
            if (this.Data.Count <= 0) return null;
            var lst = new scg::List<int>();
            for (int i = 0; i < this.Data.Count; i++) lst.Add(i);
            return lst;
        }
    }
    public int Count {
        get { return this.Data.Count; }
    }
    private static readonly pb::MessageParser<ConfigAptitudeUnlock> _parser = new pb::MessageParser<ConfigAptitudeUnlock>(() => new ConfigAptitudeUnlock());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigAptitudeUnlock> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigAptitudeUnlockReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigAptitudeUnlock() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigAptitudeUnlock(ConfigAptitudeUnlock other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigAptitudeUnlock Clone() {
      return new ConfigAptitudeUnlock(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Config.ConfigAptitudeUnlockUnit> _repeated_data_codec
        = pb::FieldCodec.ForMessage(10, global::Config.ConfigAptitudeUnlockUnit.Parser);
    private readonly pbc::RepeatedField<global::Config.ConfigAptitudeUnlockUnit> data_ = new pbc::RepeatedField<global::Config.ConfigAptitudeUnlockUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Config.ConfigAptitudeUnlockUnit> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigAptitudeUnlock);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigAptitudeUnlock other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigAptitudeUnlock other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code

