// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigChapterUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigChapterUnit.proto</summary>
  public static partial class ConfigChapterUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigChapterUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigChapterUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDb25maWdDaGFwdGVyVW5pdC5wcm90bxIGQ29uZmlnInIKEUNvbmZpZ0No",
            "YXB0ZXJVbml0EgoKAklkGAEgASgFEhAKCE5hbWVOb3RlGAIgASgJEgwKBE5h",
            "bWUYAyABKAkSEQoJTmFtZVBhcmFtGAQgASgJEg4KBlNjZW5lcxgFIAEoBRIO",
            "CgZNYXBQb3MYBiABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigChapterUnit), global::Config.ConfigChapterUnit.Parser, new[]{ "Id", "NameNote", "Name", "NameParam", "Scenes", "MapPos" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigChapterUnit : pb::IMessage<ConfigChapterUnit> {
    private static readonly pb::MessageParser<ConfigChapterUnit> _parser = new pb::MessageParser<ConfigChapterUnit>(() => new ConfigChapterUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigChapterUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigChapterUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigChapterUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigChapterUnit(ConfigChapterUnit other) : this() {
      id_ = other.id_;
      nameNote_ = other.nameNote_;
      name_ = other.name_;
      nameParam_ = other.nameParam_;
      scenes_ = other.scenes_;
      mapPos_ = other.mapPos_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigChapterUnit Clone() {
      return new ConfigChapterUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "NameNote" field.</summary>
    public const int NameNoteFieldNumber = 2;
    private string nameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameNote {
      get { return nameNote_; }
      set {
        nameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NameParam" field.</summary>
    public const int NameParamFieldNumber = 4;
    private string nameParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameParam {
      get { return nameParam_; }
      set {
        nameParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Scenes" field.</summary>
    public const int ScenesFieldNumber = 5;
    private int scenes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Scenes {
      get { return scenes_; }
      set {
        scenes_ = value;
      }
    }

    /// <summary>Field number for the "MapPos" field.</summary>
    public const int MapPosFieldNumber = 6;
    private string mapPos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MapPos {
      get { return mapPos_; }
      set {
        mapPos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigChapterUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigChapterUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NameNote != other.NameNote) return false;
      if (Name != other.Name) return false;
      if (NameParam != other.NameParam) return false;
      if (Scenes != other.Scenes) return false;
      if (MapPos != other.MapPos) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (NameNote.Length != 0) hash ^= NameNote.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (NameParam.Length != 0) hash ^= NameParam.GetHashCode();
      if (Scenes != 0) hash ^= Scenes.GetHashCode();
      if (MapPos.Length != 0) hash ^= MapPos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (NameNote.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameNote);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameParam.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameParam);
      }
      if (Scenes != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Scenes);
      }
      if (MapPos.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MapPos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (NameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNote);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (NameParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameParam);
      }
      if (Scenes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Scenes);
      }
      if (MapPos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MapPos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigChapterUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.NameNote.Length != 0) {
        NameNote = other.NameNote;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.NameParam.Length != 0) {
        NameParam = other.NameParam;
      }
      if (other.Scenes != 0) {
        Scenes = other.Scenes;
      }
      if (other.MapPos.Length != 0) {
        MapPos = other.MapPos;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            NameNote = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameParam = input.ReadString();
            break;
          }
          case 40: {
            Scenes = input.ReadInt32();
            break;
          }
          case 50: {
            MapPos = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
