// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigFirstReward.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using Engine;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigFirstReward.proto</summary>
  public static partial class ConfigFirstRewardReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigFirstReward.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigFirstRewardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDb25maWdGaXJzdFJld2FyZC5wcm90bxIGQ29uZmlnGhtDb25maWdGaXJz",
            "dFJld2FyZFVuaXQucHJvdG8ikgEKEUNvbmZpZ0ZpcnN0UmV3YXJkEjEKBGRh",
            "dGEYASADKAsyIy5Db25maWcuQ29uZmlnRmlyc3RSZXdhcmQuRGF0YUVudHJ5",
            "GkoKCURhdGFFbnRyeRILCgNrZXkYASABKAUSLAoFdmFsdWUYAiABKAsyHS5D",
            "b25maWcuQ29uZmlnRmlyc3RSZXdhcmRVbml0OgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Config.ConfigFirstRewardUnitReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigFirstReward), global::Config.ConfigFirstReward.Parser, new[]{ "Data" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigFirstReward : pb::IMessage<ConfigFirstReward>, EngineBase.IConfigBase {
    
    public static ConfigFirstReward GetNewConfig(byte[] bytes) { 
        if (bytes == null) return null;
        ConfigFirstReward config = (ConfigFirstReward)ConfigFirstReward.Descriptor.Parser.ParseFrom(bytes);
        return config;
    }
    public ConfigFirstRewardUnit Get(int key) {
        ConfigFirstRewardUnit value;
        if (this.Data.TryGetValue(key, out value))
            return value;
        return null;
    }
    public scg::ICollection<int> Keys {
        get { return this.Data.Keys; }
    }
    public int Count {
        get { return this.Data.Count; }
    }
    private static readonly pb::MessageParser<ConfigFirstReward> _parser = new pb::MessageParser<ConfigFirstReward>(() => new ConfigFirstReward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigFirstReward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigFirstRewardReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigFirstReward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigFirstReward(ConfigFirstReward other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigFirstReward Clone() {
      return new ConfigFirstReward(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Config.ConfigFirstRewardUnit>.Codec _map_data_codec
        = new pbc::MapField<int, global::Config.ConfigFirstRewardUnit>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::Config.ConfigFirstRewardUnit.Parser), 10);
    private readonly pbc::MapField<int, global::Config.ConfigFirstRewardUnit> data_ = new pbc::MapField<int, global::Config.ConfigFirstRewardUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Config.ConfigFirstRewardUnit> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigFirstReward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigFirstReward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Data.Equals(other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      data_.WriteTo(output, _map_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_map_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigFirstReward other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _map_data_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code

