// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigHeroSkillUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigHeroSkillUnit.proto</summary>
  public static partial class ConfigHeroSkillUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigHeroSkillUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigHeroSkillUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDb25maWdIZXJvU2tpbGxVbml0LnByb3RvEgZDb25maWciogEKE0NvbmZp",
            "Z0hlcm9Ta2lsbFVuaXQSCgoCSWQYASABKAUSDAoESGVybxgCIAEoBRIVCg1T",
            "a2lsbE5hbWVOb3RlGAMgASgJEhEKCVNraWxsTmFtZRgEIAEoCRISCgpTa2ls",
            "bExldmVsGAUgASgFEhMKC1NraWxsRGFtYWdlGAYgASgFEhAKCFNraWxsR2Vt",
            "GAcgASgFEgwKBEdvbGQYCCABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigHeroSkillUnit), global::Config.ConfigHeroSkillUnit.Parser, new[]{ "Id", "Hero", "SkillNameNote", "SkillName", "SkillLevel", "SkillDamage", "SkillGem", "Gold" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigHeroSkillUnit : pb::IMessage<ConfigHeroSkillUnit> {
    private static readonly pb::MessageParser<ConfigHeroSkillUnit> _parser = new pb::MessageParser<ConfigHeroSkillUnit>(() => new ConfigHeroSkillUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigHeroSkillUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigHeroSkillUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHeroSkillUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHeroSkillUnit(ConfigHeroSkillUnit other) : this() {
      id_ = other.id_;
      hero_ = other.hero_;
      skillNameNote_ = other.skillNameNote_;
      skillName_ = other.skillName_;
      skillLevel_ = other.skillLevel_;
      skillDamage_ = other.skillDamage_;
      skillGem_ = other.skillGem_;
      gold_ = other.gold_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHeroSkillUnit Clone() {
      return new ConfigHeroSkillUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Hero" field.</summary>
    public const int HeroFieldNumber = 2;
    private int hero_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hero {
      get { return hero_; }
      set {
        hero_ = value;
      }
    }

    /// <summary>Field number for the "SkillNameNote" field.</summary>
    public const int SkillNameNoteFieldNumber = 3;
    private string skillNameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SkillNameNote {
      get { return skillNameNote_; }
      set {
        skillNameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SkillName" field.</summary>
    public const int SkillNameFieldNumber = 4;
    private string skillName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SkillName {
      get { return skillName_; }
      set {
        skillName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SkillLevel" field.</summary>
    public const int SkillLevelFieldNumber = 5;
    private int skillLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillLevel {
      get { return skillLevel_; }
      set {
        skillLevel_ = value;
      }
    }

    /// <summary>Field number for the "SkillDamage" field.</summary>
    public const int SkillDamageFieldNumber = 6;
    private int skillDamage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillDamage {
      get { return skillDamage_; }
      set {
        skillDamage_ = value;
      }
    }

    /// <summary>Field number for the "SkillGem" field.</summary>
    public const int SkillGemFieldNumber = 7;
    private int skillGem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillGem {
      get { return skillGem_; }
      set {
        skillGem_ = value;
      }
    }

    /// <summary>Field number for the "Gold" field.</summary>
    public const int GoldFieldNumber = 8;
    private int gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigHeroSkillUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigHeroSkillUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Hero != other.Hero) return false;
      if (SkillNameNote != other.SkillNameNote) return false;
      if (SkillName != other.SkillName) return false;
      if (SkillLevel != other.SkillLevel) return false;
      if (SkillDamage != other.SkillDamage) return false;
      if (SkillGem != other.SkillGem) return false;
      if (Gold != other.Gold) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Hero != 0) hash ^= Hero.GetHashCode();
      if (SkillNameNote.Length != 0) hash ^= SkillNameNote.GetHashCode();
      if (SkillName.Length != 0) hash ^= SkillName.GetHashCode();
      if (SkillLevel != 0) hash ^= SkillLevel.GetHashCode();
      if (SkillDamage != 0) hash ^= SkillDamage.GetHashCode();
      if (SkillGem != 0) hash ^= SkillGem.GetHashCode();
      if (Gold != 0) hash ^= Gold.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Hero != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Hero);
      }
      if (SkillNameNote.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SkillNameNote);
      }
      if (SkillName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SkillName);
      }
      if (SkillLevel != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SkillLevel);
      }
      if (SkillDamage != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SkillDamage);
      }
      if (SkillGem != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(SkillGem);
      }
      if (Gold != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Gold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Hero != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hero);
      }
      if (SkillNameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SkillNameNote);
      }
      if (SkillName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SkillName);
      }
      if (SkillLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillLevel);
      }
      if (SkillDamage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillDamage);
      }
      if (SkillGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillGem);
      }
      if (Gold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigHeroSkillUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Hero != 0) {
        Hero = other.Hero;
      }
      if (other.SkillNameNote.Length != 0) {
        SkillNameNote = other.SkillNameNote;
      }
      if (other.SkillName.Length != 0) {
        SkillName = other.SkillName;
      }
      if (other.SkillLevel != 0) {
        SkillLevel = other.SkillLevel;
      }
      if (other.SkillDamage != 0) {
        SkillDamage = other.SkillDamage;
      }
      if (other.SkillGem != 0) {
        SkillGem = other.SkillGem;
      }
      if (other.Gold != 0) {
        Gold = other.Gold;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Hero = input.ReadInt32();
            break;
          }
          case 26: {
            SkillNameNote = input.ReadString();
            break;
          }
          case 34: {
            SkillName = input.ReadString();
            break;
          }
          case 40: {
            SkillLevel = input.ReadInt32();
            break;
          }
          case 48: {
            SkillDamage = input.ReadInt32();
            break;
          }
          case 56: {
            SkillGem = input.ReadInt32();
            break;
          }
          case 64: {
            Gold = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
