// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigBuffActionTemplate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using Engine;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigBuffActionTemplate.proto</summary>
  public static partial class ConfigBuffActionTemplateReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigBuffActionTemplate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigBuffActionTemplateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Db25maWdCdWZmQWN0aW9uVGVtcGxhdGUucHJvdG8SBkNvbmZpZxoiQ29u",
            "ZmlnQnVmZkFjdGlvblRlbXBsYXRlVW5pdC5wcm90byKnAQoYQ29uZmlnQnVm",
            "ZkFjdGlvblRlbXBsYXRlEjgKBGRhdGEYASADKAsyKi5Db25maWcuQ29uZmln",
            "QnVmZkFjdGlvblRlbXBsYXRlLkRhdGFFbnRyeRpRCglEYXRhRW50cnkSCwoD",
            "a2V5GAEgASgFEjMKBXZhbHVlGAIgASgLMiQuQ29uZmlnLkNvbmZpZ0J1ZmZB",
            "Y3Rpb25UZW1wbGF0ZVVuaXQ6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Config.ConfigBuffActionTemplateUnitReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigBuffActionTemplate), global::Config.ConfigBuffActionTemplate.Parser, new[]{ "Data" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigBuffActionTemplate : pb::IMessage<ConfigBuffActionTemplate>, EngineBase.IConfigBase {
    
    public static ConfigBuffActionTemplate GetNewConfig(byte[] bytes) { 
        if (bytes == null) return null;
        ConfigBuffActionTemplate config = (ConfigBuffActionTemplate)ConfigBuffActionTemplate.Descriptor.Parser.ParseFrom(bytes);
        return config;
    }
    public ConfigBuffActionTemplateUnit Get(int key) {
        ConfigBuffActionTemplateUnit value;
        if (this.Data.TryGetValue(key, out value))
            return value;
        return null;
    }
    public scg::ICollection<int> Keys {
        get { return this.Data.Keys; }
    }
    public int Count {
        get { return this.Data.Count; }
    }
    private static readonly pb::MessageParser<ConfigBuffActionTemplate> _parser = new pb::MessageParser<ConfigBuffActionTemplate>(() => new ConfigBuffActionTemplate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigBuffActionTemplate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigBuffActionTemplateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigBuffActionTemplate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigBuffActionTemplate(ConfigBuffActionTemplate other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigBuffActionTemplate Clone() {
      return new ConfigBuffActionTemplate(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Config.ConfigBuffActionTemplateUnit>.Codec _map_data_codec
        = new pbc::MapField<int, global::Config.ConfigBuffActionTemplateUnit>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::Config.ConfigBuffActionTemplateUnit.Parser), 10);
    private readonly pbc::MapField<int, global::Config.ConfigBuffActionTemplateUnit> data_ = new pbc::MapField<int, global::Config.ConfigBuffActionTemplateUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Config.ConfigBuffActionTemplateUnit> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigBuffActionTemplate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigBuffActionTemplate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Data.Equals(other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      data_.WriteTo(output, _map_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_map_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigBuffActionTemplate other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _map_data_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code

