// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigTreasureChestUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigTreasureChestUnit.proto</summary>
  public static partial class ConfigTreasureChestUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigTreasureChestUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigTreasureChestUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Db25maWdUcmVhc3VyZUNoZXN0VW5pdC5wcm90bxIGQ29uZmlnIrwBChdD",
            "b25maWdUcmVhc3VyZUNoZXN0VW5pdBIKCgJJZBgBIAEoBRIOCgZOZXh0SUQY",
            "AiABKAUSEQoJR29sZENvaW5zGAMgASgJEhQKDEdvbGRDb2luc051bRgEIAEo",
            "BRIPCgdDb25zdW1lGAUgASgFEg4KBlVwVGltZRgGIAEoBRISCgpRdWFsaXR5",
            "UHJvGAcgASgJEhYKDlF1YWxpdHlQcm9TaG93GAggASgJEg8KB1BhcnRQcm8Y",
            "CSABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigTreasureChestUnit), global::Config.ConfigTreasureChestUnit.Parser, new[]{ "Id", "NextID", "GoldCoins", "GoldCoinsNum", "Consume", "UpTime", "QualityPro", "QualityProShow", "PartPro" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigTreasureChestUnit : pb::IMessage<ConfigTreasureChestUnit> {
    private static readonly pb::MessageParser<ConfigTreasureChestUnit> _parser = new pb::MessageParser<ConfigTreasureChestUnit>(() => new ConfigTreasureChestUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigTreasureChestUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigTreasureChestUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTreasureChestUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTreasureChestUnit(ConfigTreasureChestUnit other) : this() {
      id_ = other.id_;
      nextID_ = other.nextID_;
      goldCoins_ = other.goldCoins_;
      goldCoinsNum_ = other.goldCoinsNum_;
      consume_ = other.consume_;
      upTime_ = other.upTime_;
      qualityPro_ = other.qualityPro_;
      qualityProShow_ = other.qualityProShow_;
      partPro_ = other.partPro_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTreasureChestUnit Clone() {
      return new ConfigTreasureChestUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "NextID" field.</summary>
    public const int NextIDFieldNumber = 2;
    private int nextID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NextID {
      get { return nextID_; }
      set {
        nextID_ = value;
      }
    }

    /// <summary>Field number for the "GoldCoins" field.</summary>
    public const int GoldCoinsFieldNumber = 3;
    private string goldCoins_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GoldCoins {
      get { return goldCoins_; }
      set {
        goldCoins_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "GoldCoinsNum" field.</summary>
    public const int GoldCoinsNumFieldNumber = 4;
    private int goldCoinsNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoldCoinsNum {
      get { return goldCoinsNum_; }
      set {
        goldCoinsNum_ = value;
      }
    }

    /// <summary>Field number for the "Consume" field.</summary>
    public const int ConsumeFieldNumber = 5;
    private int consume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Consume {
      get { return consume_; }
      set {
        consume_ = value;
      }
    }

    /// <summary>Field number for the "UpTime" field.</summary>
    public const int UpTimeFieldNumber = 6;
    private int upTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UpTime {
      get { return upTime_; }
      set {
        upTime_ = value;
      }
    }

    /// <summary>Field number for the "QualityPro" field.</summary>
    public const int QualityProFieldNumber = 7;
    private string qualityPro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string QualityPro {
      get { return qualityPro_; }
      set {
        qualityPro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "QualityProShow" field.</summary>
    public const int QualityProShowFieldNumber = 8;
    private string qualityProShow_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string QualityProShow {
      get { return qualityProShow_; }
      set {
        qualityProShow_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PartPro" field.</summary>
    public const int PartProFieldNumber = 9;
    private string partPro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PartPro {
      get { return partPro_; }
      set {
        partPro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigTreasureChestUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigTreasureChestUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NextID != other.NextID) return false;
      if (GoldCoins != other.GoldCoins) return false;
      if (GoldCoinsNum != other.GoldCoinsNum) return false;
      if (Consume != other.Consume) return false;
      if (UpTime != other.UpTime) return false;
      if (QualityPro != other.QualityPro) return false;
      if (QualityProShow != other.QualityProShow) return false;
      if (PartPro != other.PartPro) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (NextID != 0) hash ^= NextID.GetHashCode();
      if (GoldCoins.Length != 0) hash ^= GoldCoins.GetHashCode();
      if (GoldCoinsNum != 0) hash ^= GoldCoinsNum.GetHashCode();
      if (Consume != 0) hash ^= Consume.GetHashCode();
      if (UpTime != 0) hash ^= UpTime.GetHashCode();
      if (QualityPro.Length != 0) hash ^= QualityPro.GetHashCode();
      if (QualityProShow.Length != 0) hash ^= QualityProShow.GetHashCode();
      if (PartPro.Length != 0) hash ^= PartPro.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (NextID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NextID);
      }
      if (GoldCoins.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GoldCoins);
      }
      if (GoldCoinsNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(GoldCoinsNum);
      }
      if (Consume != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Consume);
      }
      if (UpTime != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(UpTime);
      }
      if (QualityPro.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(QualityPro);
      }
      if (QualityProShow.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(QualityProShow);
      }
      if (PartPro.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PartPro);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (NextID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NextID);
      }
      if (GoldCoins.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GoldCoins);
      }
      if (GoldCoinsNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoldCoinsNum);
      }
      if (Consume != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Consume);
      }
      if (UpTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpTime);
      }
      if (QualityPro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QualityPro);
      }
      if (QualityProShow.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QualityProShow);
      }
      if (PartPro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartPro);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigTreasureChestUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.NextID != 0) {
        NextID = other.NextID;
      }
      if (other.GoldCoins.Length != 0) {
        GoldCoins = other.GoldCoins;
      }
      if (other.GoldCoinsNum != 0) {
        GoldCoinsNum = other.GoldCoinsNum;
      }
      if (other.Consume != 0) {
        Consume = other.Consume;
      }
      if (other.UpTime != 0) {
        UpTime = other.UpTime;
      }
      if (other.QualityPro.Length != 0) {
        QualityPro = other.QualityPro;
      }
      if (other.QualityProShow.Length != 0) {
        QualityProShow = other.QualityProShow;
      }
      if (other.PartPro.Length != 0) {
        PartPro = other.PartPro;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            NextID = input.ReadInt32();
            break;
          }
          case 26: {
            GoldCoins = input.ReadString();
            break;
          }
          case 32: {
            GoldCoinsNum = input.ReadInt32();
            break;
          }
          case 40: {
            Consume = input.ReadInt32();
            break;
          }
          case 48: {
            UpTime = input.ReadInt32();
            break;
          }
          case 58: {
            QualityPro = input.ReadString();
            break;
          }
          case 66: {
            QualityProShow = input.ReadString();
            break;
          }
          case 74: {
            PartPro = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
