// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigLoreSkiirateUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigLoreSkiirateUnit.proto</summary>
  public static partial class ConfigLoreSkiirateUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigLoreSkiirateUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigLoreSkiirateUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxDb25maWdMb3JlU2tpaXJhdGVVbml0LnByb3RvEgZDb25maWciYQoWQ29u",
            "ZmlnTG9yZVNraWlyYXRlVW5pdBIKCgJJZBgBIAEoBRISCgpTa2lsbEdyb3Vw",
            "GAIgASgFEg0KBVNraWxsGAMgASgFEgwKBFJhdGUYBCABKAUSCgoCTFYYBSAB",
            "KAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigLoreSkiirateUnit), global::Config.ConfigLoreSkiirateUnit.Parser, new[]{ "Id", "SkillGroup", "Skill", "Rate", "LV" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigLoreSkiirateUnit : pb::IMessage<ConfigLoreSkiirateUnit> {
    private static readonly pb::MessageParser<ConfigLoreSkiirateUnit> _parser = new pb::MessageParser<ConfigLoreSkiirateUnit>(() => new ConfigLoreSkiirateUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigLoreSkiirateUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigLoreSkiirateUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigLoreSkiirateUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigLoreSkiirateUnit(ConfigLoreSkiirateUnit other) : this() {
      id_ = other.id_;
      skillGroup_ = other.skillGroup_;
      skill_ = other.skill_;
      rate_ = other.rate_;
      lV_ = other.lV_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigLoreSkiirateUnit Clone() {
      return new ConfigLoreSkiirateUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "SkillGroup" field.</summary>
    public const int SkillGroupFieldNumber = 2;
    private int skillGroup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillGroup {
      get { return skillGroup_; }
      set {
        skillGroup_ = value;
      }
    }

    /// <summary>Field number for the "Skill" field.</summary>
    public const int SkillFieldNumber = 3;
    private int skill_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Skill {
      get { return skill_; }
      set {
        skill_ = value;
      }
    }

    /// <summary>Field number for the "Rate" field.</summary>
    public const int RateFieldNumber = 4;
    private int rate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "LV" field.</summary>
    public const int LVFieldNumber = 5;
    private int lV_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LV {
      get { return lV_; }
      set {
        lV_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigLoreSkiirateUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigLoreSkiirateUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (SkillGroup != other.SkillGroup) return false;
      if (Skill != other.Skill) return false;
      if (Rate != other.Rate) return false;
      if (LV != other.LV) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (SkillGroup != 0) hash ^= SkillGroup.GetHashCode();
      if (Skill != 0) hash ^= Skill.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (LV != 0) hash ^= LV.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (SkillGroup != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SkillGroup);
      }
      if (Skill != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Skill);
      }
      if (Rate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Rate);
      }
      if (LV != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(LV);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (SkillGroup != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillGroup);
      }
      if (Skill != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (LV != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LV);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigLoreSkiirateUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.SkillGroup != 0) {
        SkillGroup = other.SkillGroup;
      }
      if (other.Skill != 0) {
        Skill = other.Skill;
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      if (other.LV != 0) {
        LV = other.LV;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            SkillGroup = input.ReadInt32();
            break;
          }
          case 24: {
            Skill = input.ReadInt32();
            break;
          }
          case 32: {
            Rate = input.ReadInt32();
            break;
          }
          case 40: {
            LV = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
