// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigPetBasisUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigPetBasisUnit.proto</summary>
  public static partial class ConfigPetBasisUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigPetBasisUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigPetBasisUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDb25maWdQZXRCYXNpc1VuaXQucHJvdG8SBkNvbmZpZyLTAgoSQ29uZmln",
            "UGV0QmFzaXNVbml0EgoKAklkGAEgASgFEhAKCE5hbWVOb3RlGAIgASgJEgwK",
            "BE5hbWUYAyABKAkSDAoEVHlwZRgEIAEoBRIPCgdRdWFsaXR5GAUgASgFEhUK",
            "DUF0dGFja1NraWxsSWQYBiABKAUSFAoMU2tpbGxHcm91cElkGAcgASgFEhEK",
            "CVN0b3J5Tm90ZRgIIAEoCRINCgVTdG9yeRgJIAEoCRIQCghJY29uUGF0aBgK",
            "IAEoCRIVCg1GdWxsQm9keUltYWdlGAsgASgJEhAKCFBldE1vZGVsGAwgASgJ",
            "Eg8KB0luaGVyaXQYDSABKAUSDQoFRmxvb3IYDiABKAUSDQoFVXBwZXIYDyAB",
            "KAUSEAoIQXRrU3BlZWQYECABKAUSEgoKTW9kZWxTY2FsZRgRIAEoBRITCgtQ",
            "ZXRRdW90ZXNJZBgSIAMoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigPetBasisUnit), global::Config.ConfigPetBasisUnit.Parser, new[]{ "Id", "NameNote", "Name", "Type", "Quality", "AttackSkillId", "SkillGroupId", "StoryNote", "Story", "IconPath", "FullBodyImage", "PetModel", "Inherit", "Floor", "Upper", "AtkSpeed", "ModelScale", "PetQuotesId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigPetBasisUnit : pb::IMessage<ConfigPetBasisUnit> {
    private static readonly pb::MessageParser<ConfigPetBasisUnit> _parser = new pb::MessageParser<ConfigPetBasisUnit>(() => new ConfigPetBasisUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigPetBasisUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigPetBasisUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetBasisUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetBasisUnit(ConfigPetBasisUnit other) : this() {
      id_ = other.id_;
      nameNote_ = other.nameNote_;
      name_ = other.name_;
      type_ = other.type_;
      quality_ = other.quality_;
      attackSkillId_ = other.attackSkillId_;
      skillGroupId_ = other.skillGroupId_;
      storyNote_ = other.storyNote_;
      story_ = other.story_;
      iconPath_ = other.iconPath_;
      fullBodyImage_ = other.fullBodyImage_;
      petModel_ = other.petModel_;
      inherit_ = other.inherit_;
      floor_ = other.floor_;
      upper_ = other.upper_;
      atkSpeed_ = other.atkSpeed_;
      modelScale_ = other.modelScale_;
      petQuotesId_ = other.petQuotesId_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetBasisUnit Clone() {
      return new ConfigPetBasisUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "NameNote" field.</summary>
    public const int NameNoteFieldNumber = 2;
    private string nameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameNote {
      get { return nameNote_; }
      set {
        nameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 4;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Quality" field.</summary>
    public const int QualityFieldNumber = 5;
    private int quality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "AttackSkillId" field.</summary>
    public const int AttackSkillIdFieldNumber = 6;
    private int attackSkillId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AttackSkillId {
      get { return attackSkillId_; }
      set {
        attackSkillId_ = value;
      }
    }

    /// <summary>Field number for the "SkillGroupId" field.</summary>
    public const int SkillGroupIdFieldNumber = 7;
    private int skillGroupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillGroupId {
      get { return skillGroupId_; }
      set {
        skillGroupId_ = value;
      }
    }

    /// <summary>Field number for the "StoryNote" field.</summary>
    public const int StoryNoteFieldNumber = 8;
    private string storyNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StoryNote {
      get { return storyNote_; }
      set {
        storyNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Story" field.</summary>
    public const int StoryFieldNumber = 9;
    private string story_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Story {
      get { return story_; }
      set {
        story_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IconPath" field.</summary>
    public const int IconPathFieldNumber = 10;
    private string iconPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IconPath {
      get { return iconPath_; }
      set {
        iconPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FullBodyImage" field.</summary>
    public const int FullBodyImageFieldNumber = 11;
    private string fullBodyImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FullBodyImage {
      get { return fullBodyImage_; }
      set {
        fullBodyImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PetModel" field.</summary>
    public const int PetModelFieldNumber = 12;
    private string petModel_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PetModel {
      get { return petModel_; }
      set {
        petModel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Inherit" field.</summary>
    public const int InheritFieldNumber = 13;
    private int inherit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Inherit {
      get { return inherit_; }
      set {
        inherit_ = value;
      }
    }

    /// <summary>Field number for the "Floor" field.</summary>
    public const int FloorFieldNumber = 14;
    private int floor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Floor {
      get { return floor_; }
      set {
        floor_ = value;
      }
    }

    /// <summary>Field number for the "Upper" field.</summary>
    public const int UpperFieldNumber = 15;
    private int upper_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Upper {
      get { return upper_; }
      set {
        upper_ = value;
      }
    }

    /// <summary>Field number for the "AtkSpeed" field.</summary>
    public const int AtkSpeedFieldNumber = 16;
    private int atkSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AtkSpeed {
      get { return atkSpeed_; }
      set {
        atkSpeed_ = value;
      }
    }

    /// <summary>Field number for the "ModelScale" field.</summary>
    public const int ModelScaleFieldNumber = 17;
    private int modelScale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ModelScale {
      get { return modelScale_; }
      set {
        modelScale_ = value;
      }
    }

    /// <summary>Field number for the "PetQuotesId" field.</summary>
    public const int PetQuotesIdFieldNumber = 18;
    private static readonly pb::FieldCodec<int> _repeated_petQuotesId_codec
        = pb::FieldCodec.ForInt32(146);
    private readonly pbc::RepeatedField<int> petQuotesId_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> PetQuotesId {
      get { return petQuotesId_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigPetBasisUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigPetBasisUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NameNote != other.NameNote) return false;
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (Quality != other.Quality) return false;
      if (AttackSkillId != other.AttackSkillId) return false;
      if (SkillGroupId != other.SkillGroupId) return false;
      if (StoryNote != other.StoryNote) return false;
      if (Story != other.Story) return false;
      if (IconPath != other.IconPath) return false;
      if (FullBodyImage != other.FullBodyImage) return false;
      if (PetModel != other.PetModel) return false;
      if (Inherit != other.Inherit) return false;
      if (Floor != other.Floor) return false;
      if (Upper != other.Upper) return false;
      if (AtkSpeed != other.AtkSpeed) return false;
      if (ModelScale != other.ModelScale) return false;
      if(!petQuotesId_.Equals(other.petQuotesId_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (NameNote.Length != 0) hash ^= NameNote.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Quality != 0) hash ^= Quality.GetHashCode();
      if (AttackSkillId != 0) hash ^= AttackSkillId.GetHashCode();
      if (SkillGroupId != 0) hash ^= SkillGroupId.GetHashCode();
      if (StoryNote.Length != 0) hash ^= StoryNote.GetHashCode();
      if (Story.Length != 0) hash ^= Story.GetHashCode();
      if (IconPath.Length != 0) hash ^= IconPath.GetHashCode();
      if (FullBodyImage.Length != 0) hash ^= FullBodyImage.GetHashCode();
      if (PetModel.Length != 0) hash ^= PetModel.GetHashCode();
      if (Inherit != 0) hash ^= Inherit.GetHashCode();
      if (Floor != 0) hash ^= Floor.GetHashCode();
      if (Upper != 0) hash ^= Upper.GetHashCode();
      if (AtkSpeed != 0) hash ^= AtkSpeed.GetHashCode();
      if (ModelScale != 0) hash ^= ModelScale.GetHashCode();
      hash ^= petQuotesId_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (NameNote.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameNote);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Type != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Type);
      }
      if (Quality != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Quality);
      }
      if (AttackSkillId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(AttackSkillId);
      }
      if (SkillGroupId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(SkillGroupId);
      }
      if (StoryNote.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StoryNote);
      }
      if (Story.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Story);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(IconPath);
      }
      if (FullBodyImage.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(FullBodyImage);
      }
      if (PetModel.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(PetModel);
      }
      if (Inherit != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Inherit);
      }
      if (Floor != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Floor);
      }
      if (Upper != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Upper);
      }
      if (AtkSpeed != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(AtkSpeed);
      }
      if (ModelScale != 0) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(ModelScale);
      }
      petQuotesId_.WriteTo(output, _repeated_petQuotesId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (NameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNote);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
      }
      if (AttackSkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackSkillId);
      }
      if (SkillGroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillGroupId);
      }
      if (StoryNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StoryNote);
      }
      if (Story.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Story);
      }
      if (IconPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconPath);
      }
      if (FullBodyImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullBodyImage);
      }
      if (PetModel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PetModel);
      }
      if (Inherit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Inherit);
      }
      if (Floor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Floor);
      }
      if (Upper != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Upper);
      }
      if (AtkSpeed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(AtkSpeed);
      }
      if (ModelScale != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(ModelScale);
      }
      size += petQuotesId_.CalculateSize(_repeated_petQuotesId_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigPetBasisUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.NameNote.Length != 0) {
        NameNote = other.NameNote;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Quality != 0) {
        Quality = other.Quality;
      }
      if (other.AttackSkillId != 0) {
        AttackSkillId = other.AttackSkillId;
      }
      if (other.SkillGroupId != 0) {
        SkillGroupId = other.SkillGroupId;
      }
      if (other.StoryNote.Length != 0) {
        StoryNote = other.StoryNote;
      }
      if (other.Story.Length != 0) {
        Story = other.Story;
      }
      if (other.IconPath.Length != 0) {
        IconPath = other.IconPath;
      }
      if (other.FullBodyImage.Length != 0) {
        FullBodyImage = other.FullBodyImage;
      }
      if (other.PetModel.Length != 0) {
        PetModel = other.PetModel;
      }
      if (other.Inherit != 0) {
        Inherit = other.Inherit;
      }
      if (other.Floor != 0) {
        Floor = other.Floor;
      }
      if (other.Upper != 0) {
        Upper = other.Upper;
      }
      if (other.AtkSpeed != 0) {
        AtkSpeed = other.AtkSpeed;
      }
      if (other.ModelScale != 0) {
        ModelScale = other.ModelScale;
      }
      petQuotesId_.Add(other.petQuotesId_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            NameNote = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            Type = input.ReadInt32();
            break;
          }
          case 40: {
            Quality = input.ReadInt32();
            break;
          }
          case 48: {
            AttackSkillId = input.ReadInt32();
            break;
          }
          case 56: {
            SkillGroupId = input.ReadInt32();
            break;
          }
          case 66: {
            StoryNote = input.ReadString();
            break;
          }
          case 74: {
            Story = input.ReadString();
            break;
          }
          case 82: {
            IconPath = input.ReadString();
            break;
          }
          case 90: {
            FullBodyImage = input.ReadString();
            break;
          }
          case 98: {
            PetModel = input.ReadString();
            break;
          }
          case 104: {
            Inherit = input.ReadInt32();
            break;
          }
          case 112: {
            Floor = input.ReadInt32();
            break;
          }
          case 120: {
            Upper = input.ReadInt32();
            break;
          }
          case 128: {
            AtkSpeed = input.ReadInt32();
            break;
          }
          case 136: {
            ModelScale = input.ReadInt32();
            break;
          }
          case 146:
          case 144: {
            petQuotesId_.AddEntriesFrom(input, _repeated_petQuotesId_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
