// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigHolyUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigHolyUnit.proto</summary>
  public static partial class ConfigHolyUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigHolyUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigHolyUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb25maWdIb2x5VW5pdC5wcm90bxIGQ29uZmlnIsUBCg5Db25maWdIb2x5",
            "VW5pdBIKCgJJZBgBIAEoBRIOCgZIb2x5SWQYAiABKAUSDAoETmFtZRgDIAEo",
            "CRIOCgZOb3RlczEYBCABKAkSDAoEVHlwZRgFIAEoBRIKCgJMdhgGIAEoBRIQ",
            "CghDb25zdW1lMRgHIAEoBRIQCghDb25zdW1lMhgIIAEoBRILCgNEb2MYCSAB",
            "KAkSDgoGTm90ZXMyGAogASgJEg4KBkNvbW1vbhgLIAEoCRIOCgZJdGVtSUQY",
            "DCABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigHolyUnit), global::Config.ConfigHolyUnit.Parser, new[]{ "Id", "HolyId", "Name", "Notes1", "Type", "Lv", "Consume1", "Consume2", "Doc", "Notes2", "Common", "ItemID" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigHolyUnit : pb::IMessage<ConfigHolyUnit> {
    private static readonly pb::MessageParser<ConfigHolyUnit> _parser = new pb::MessageParser<ConfigHolyUnit>(() => new ConfigHolyUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigHolyUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigHolyUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHolyUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHolyUnit(ConfigHolyUnit other) : this() {
      id_ = other.id_;
      holyId_ = other.holyId_;
      name_ = other.name_;
      notes1_ = other.notes1_;
      type_ = other.type_;
      lv_ = other.lv_;
      consume1_ = other.consume1_;
      consume2_ = other.consume2_;
      doc_ = other.doc_;
      notes2_ = other.notes2_;
      common_ = other.common_;
      itemID_ = other.itemID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHolyUnit Clone() {
      return new ConfigHolyUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "HolyId" field.</summary>
    public const int HolyIdFieldNumber = 2;
    private int holyId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int HolyId {
      get { return holyId_; }
      set {
        holyId_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Notes1" field.</summary>
    public const int Notes1FieldNumber = 4;
    private string notes1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Notes1 {
      get { return notes1_; }
      set {
        notes1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 5;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Lv" field.</summary>
    public const int LvFieldNumber = 6;
    private int lv_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Lv {
      get { return lv_; }
      set {
        lv_ = value;
      }
    }

    /// <summary>Field number for the "Consume1" field.</summary>
    public const int Consume1FieldNumber = 7;
    private int consume1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Consume1 {
      get { return consume1_; }
      set {
        consume1_ = value;
      }
    }

    /// <summary>Field number for the "Consume2" field.</summary>
    public const int Consume2FieldNumber = 8;
    private int consume2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Consume2 {
      get { return consume2_; }
      set {
        consume2_ = value;
      }
    }

    /// <summary>Field number for the "Doc" field.</summary>
    public const int DocFieldNumber = 9;
    private string doc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Doc {
      get { return doc_; }
      set {
        doc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Notes2" field.</summary>
    public const int Notes2FieldNumber = 10;
    private string notes2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Notes2 {
      get { return notes2_; }
      set {
        notes2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Common" field.</summary>
    public const int CommonFieldNumber = 11;
    private string common_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Common {
      get { return common_; }
      set {
        common_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ItemID" field.</summary>
    public const int ItemIDFieldNumber = 12;
    private int itemID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemID {
      get { return itemID_; }
      set {
        itemID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigHolyUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigHolyUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (HolyId != other.HolyId) return false;
      if (Name != other.Name) return false;
      if (Notes1 != other.Notes1) return false;
      if (Type != other.Type) return false;
      if (Lv != other.Lv) return false;
      if (Consume1 != other.Consume1) return false;
      if (Consume2 != other.Consume2) return false;
      if (Doc != other.Doc) return false;
      if (Notes2 != other.Notes2) return false;
      if (Common != other.Common) return false;
      if (ItemID != other.ItemID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (HolyId != 0) hash ^= HolyId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Notes1.Length != 0) hash ^= Notes1.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Lv != 0) hash ^= Lv.GetHashCode();
      if (Consume1 != 0) hash ^= Consume1.GetHashCode();
      if (Consume2 != 0) hash ^= Consume2.GetHashCode();
      if (Doc.Length != 0) hash ^= Doc.GetHashCode();
      if (Notes2.Length != 0) hash ^= Notes2.GetHashCode();
      if (Common.Length != 0) hash ^= Common.GetHashCode();
      if (ItemID != 0) hash ^= ItemID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HolyId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(HolyId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Notes1.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Notes1);
      }
      if (Type != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Type);
      }
      if (Lv != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Lv);
      }
      if (Consume1 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Consume1);
      }
      if (Consume2 != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Consume2);
      }
      if (Doc.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Doc);
      }
      if (Notes2.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Notes2);
      }
      if (Common.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Common);
      }
      if (ItemID != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(ItemID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (HolyId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HolyId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Notes1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Notes1);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Lv != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lv);
      }
      if (Consume1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Consume1);
      }
      if (Consume2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Consume2);
      }
      if (Doc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Doc);
      }
      if (Notes2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Notes2);
      }
      if (Common.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Common);
      }
      if (ItemID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigHolyUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.HolyId != 0) {
        HolyId = other.HolyId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Notes1.Length != 0) {
        Notes1 = other.Notes1;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Lv != 0) {
        Lv = other.Lv;
      }
      if (other.Consume1 != 0) {
        Consume1 = other.Consume1;
      }
      if (other.Consume2 != 0) {
        Consume2 = other.Consume2;
      }
      if (other.Doc.Length != 0) {
        Doc = other.Doc;
      }
      if (other.Notes2.Length != 0) {
        Notes2 = other.Notes2;
      }
      if (other.Common.Length != 0) {
        Common = other.Common;
      }
      if (other.ItemID != 0) {
        ItemID = other.ItemID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            HolyId = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Notes1 = input.ReadString();
            break;
          }
          case 40: {
            Type = input.ReadInt32();
            break;
          }
          case 48: {
            Lv = input.ReadInt32();
            break;
          }
          case 56: {
            Consume1 = input.ReadInt32();
            break;
          }
          case 64: {
            Consume2 = input.ReadInt32();
            break;
          }
          case 74: {
            Doc = input.ReadString();
            break;
          }
          case 82: {
            Notes2 = input.ReadString();
            break;
          }
          case 90: {
            Common = input.ReadString();
            break;
          }
          case 96: {
            ItemID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
