// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigAptitudeUnlockUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigAptitudeUnlockUnit.proto</summary>
  public static partial class ConfigAptitudeUnlockUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigAptitudeUnlockUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigAptitudeUnlockUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Db25maWdBcHRpdHVkZVVubG9ja1VuaXQucHJvdG8SBkNvbmZpZyJ8ChhD",
            "b25maWdBcHRpdHVkZVVubG9ja1VuaXQSDgoGQnVmZklkGAEgASgFEgwKBE5h",
            "bWUYAiABKAkSDAoEVHlwZRgDIAEoBRINCgVQcmVJZBgEIAEoCRIKCgJMdhgF",
            "IAEoCRILCgNEb2MYBiABKAkSDAoESWNvbhgHIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigAptitudeUnlockUnit), global::Config.ConfigAptitudeUnlockUnit.Parser, new[]{ "BuffId", "Name", "Type", "PreId", "Lv", "Doc", "Icon" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigAptitudeUnlockUnit : pb::IMessage<ConfigAptitudeUnlockUnit> {
    private static readonly pb::MessageParser<ConfigAptitudeUnlockUnit> _parser = new pb::MessageParser<ConfigAptitudeUnlockUnit>(() => new ConfigAptitudeUnlockUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigAptitudeUnlockUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigAptitudeUnlockUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigAptitudeUnlockUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigAptitudeUnlockUnit(ConfigAptitudeUnlockUnit other) : this() {
      buffId_ = other.buffId_;
      name_ = other.name_;
      type_ = other.type_;
      preId_ = other.preId_;
      lv_ = other.lv_;
      doc_ = other.doc_;
      icon_ = other.icon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigAptitudeUnlockUnit Clone() {
      return new ConfigAptitudeUnlockUnit(this);
    }

    /// <summary>Field number for the "BuffId" field.</summary>
    public const int BuffIdFieldNumber = 1;
    private int buffId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuffId {
      get { return buffId_; }
      set {
        buffId_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 3;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "PreId" field.</summary>
    public const int PreIdFieldNumber = 4;
    private string preId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PreId {
      get { return preId_; }
      set {
        preId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Lv" field.</summary>
    public const int LvFieldNumber = 5;
    private string lv_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lv {
      get { return lv_; }
      set {
        lv_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Doc" field.</summary>
    public const int DocFieldNumber = 6;
    private string doc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Doc {
      get { return doc_; }
      set {
        doc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Icon" field.</summary>
    public const int IconFieldNumber = 7;
    private int icon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Icon {
      get { return icon_; }
      set {
        icon_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigAptitudeUnlockUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigAptitudeUnlockUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BuffId != other.BuffId) return false;
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (PreId != other.PreId) return false;
      if (Lv != other.Lv) return false;
      if (Doc != other.Doc) return false;
      if (Icon != other.Icon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BuffId != 0) hash ^= BuffId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (PreId.Length != 0) hash ^= PreId.GetHashCode();
      if (Lv.Length != 0) hash ^= Lv.GetHashCode();
      if (Doc.Length != 0) hash ^= Doc.GetHashCode();
      if (Icon != 0) hash ^= Icon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BuffId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BuffId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Type);
      }
      if (PreId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PreId);
      }
      if (Lv.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Lv);
      }
      if (Doc.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Doc);
      }
      if (Icon != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Icon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BuffId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (PreId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PreId);
      }
      if (Lv.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lv);
      }
      if (Doc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Doc);
      }
      if (Icon != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Icon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigAptitudeUnlockUnit other) {
      if (other == null) {
        return;
      }
      if (other.BuffId != 0) {
        BuffId = other.BuffId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.PreId.Length != 0) {
        PreId = other.PreId;
      }
      if (other.Lv.Length != 0) {
        Lv = other.Lv;
      }
      if (other.Doc.Length != 0) {
        Doc = other.Doc;
      }
      if (other.Icon != 0) {
        Icon = other.Icon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BuffId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Type = input.ReadInt32();
            break;
          }
          case 34: {
            PreId = input.ReadString();
            break;
          }
          case 42: {
            Lv = input.ReadString();
            break;
          }
          case 50: {
            Doc = input.ReadString();
            break;
          }
          case 56: {
            Icon = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
