// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigHelpUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigHelpUnit.proto</summary>
  public static partial class ConfigHelpUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigHelpUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigHelpUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb25maWdIZWxwVW5pdC5wcm90bxIGQ29uZmlnIpEBCg5Db25maWdIZWxw",
            "VW5pdBIKCgJJZBgBIAEoBRIMCgRUeXBlGAIgASgFEgwKBE5hbWUYAyABKAkS",
            "EwoLQ29udGVudE5vdGUYBCABKAkSDwoHQ29udGVudBgFIAEoCRIUCgxDb250",
            "ZW50UGFyYW0YBiABKAkSDQoFT3JkZXIYByABKAUSDAoESWNvbhgIIAEoBWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigHelpUnit), global::Config.ConfigHelpUnit.Parser, new[]{ "Id", "Type", "Name", "ContentNote", "Content", "ContentParam", "Order", "Icon" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigHelpUnit : pb::IMessage<ConfigHelpUnit> {
    private static readonly pb::MessageParser<ConfigHelpUnit> _parser = new pb::MessageParser<ConfigHelpUnit>(() => new ConfigHelpUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigHelpUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigHelpUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHelpUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHelpUnit(ConfigHelpUnit other) : this() {
      id_ = other.id_;
      type_ = other.type_;
      name_ = other.name_;
      contentNote_ = other.contentNote_;
      content_ = other.content_;
      contentParam_ = other.contentParam_;
      order_ = other.order_;
      icon_ = other.icon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigHelpUnit Clone() {
      return new ConfigHelpUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ContentNote" field.</summary>
    public const int ContentNoteFieldNumber = 4;
    private string contentNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContentNote {
      get { return contentNote_; }
      set {
        contentNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Content" field.</summary>
    public const int ContentFieldNumber = 5;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ContentParam" field.</summary>
    public const int ContentParamFieldNumber = 6;
    private string contentParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContentParam {
      get { return contentParam_; }
      set {
        contentParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Order" field.</summary>
    public const int OrderFieldNumber = 7;
    private int order_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Order {
      get { return order_; }
      set {
        order_ = value;
      }
    }

    /// <summary>Field number for the "Icon" field.</summary>
    public const int IconFieldNumber = 8;
    private int icon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Icon {
      get { return icon_; }
      set {
        icon_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigHelpUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigHelpUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (ContentNote != other.ContentNote) return false;
      if (Content != other.Content) return false;
      if (ContentParam != other.ContentParam) return false;
      if (Order != other.Order) return false;
      if (Icon != other.Icon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ContentNote.Length != 0) hash ^= ContentNote.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (ContentParam.Length != 0) hash ^= ContentParam.GetHashCode();
      if (Order != 0) hash ^= Order.GetHashCode();
      if (Icon != 0) hash ^= Icon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (ContentNote.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ContentNote);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Content);
      }
      if (ContentParam.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ContentParam);
      }
      if (Order != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Order);
      }
      if (Icon != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Icon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ContentNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentNote);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (ContentParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentParam);
      }
      if (Order != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Order);
      }
      if (Icon != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Icon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigHelpUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ContentNote.Length != 0) {
        ContentNote = other.ContentNote;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.ContentParam.Length != 0) {
        ContentParam = other.ContentParam;
      }
      if (other.Order != 0) {
        Order = other.Order;
      }
      if (other.Icon != 0) {
        Icon = other.Icon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            ContentNote = input.ReadString();
            break;
          }
          case 42: {
            Content = input.ReadString();
            break;
          }
          case 50: {
            ContentParam = input.ReadString();
            break;
          }
          case 56: {
            Order = input.ReadInt32();
            break;
          }
          case 64: {
            Icon = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
