// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigEventTaskUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigEventTaskUnit.proto</summary>
  public static partial class ConfigEventTaskUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigEventTaskUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigEventTaskUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDb25maWdFdmVudFRhc2tVbml0LnByb3RvEgZDb25maWcivQEKE0NvbmZp",
            "Z0V2ZW50VGFza1VuaXQSCgoCSWQYASABKAUSDAoEVHlwZRgCIAEoBRINCgVQ",
            "YXJhbRgDIAEoCRIMCgRSYXRlGAQgASgFEgwKBE5hbWUYBSABKAkSCwoDRG9j",
            "GAYgASgJEg4KBlJld2FyZBgHIAEoCRIQCghTeXN0ZW1JZBgIIAEoBRIQCghO",
            "YW1lTm90ZRgJIAEoCRIPCgdEb2NOb3RlGAogASgJEg8KB0NvbmR1Y3QYCyAB",
            "KAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigEventTaskUnit), global::Config.ConfigEventTaskUnit.Parser, new[]{ "Id", "Type", "Param", "Rate", "Name", "Doc", "Reward", "SystemId", "NameNote", "DocNote", "Conduct" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigEventTaskUnit : pb::IMessage<ConfigEventTaskUnit> {
    private static readonly pb::MessageParser<ConfigEventTaskUnit> _parser = new pb::MessageParser<ConfigEventTaskUnit>(() => new ConfigEventTaskUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigEventTaskUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigEventTaskUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigEventTaskUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigEventTaskUnit(ConfigEventTaskUnit other) : this() {
      id_ = other.id_;
      type_ = other.type_;
      param_ = other.param_;
      rate_ = other.rate_;
      name_ = other.name_;
      doc_ = other.doc_;
      reward_ = other.reward_;
      systemId_ = other.systemId_;
      nameNote_ = other.nameNote_;
      docNote_ = other.docNote_;
      conduct_ = other.conduct_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigEventTaskUnit Clone() {
      return new ConfigEventTaskUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Param" field.</summary>
    public const int ParamFieldNumber = 3;
    private string param_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Param {
      get { return param_; }
      set {
        param_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Rate" field.</summary>
    public const int RateFieldNumber = 4;
    private int rate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 5;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Doc" field.</summary>
    public const int DocFieldNumber = 6;
    private string doc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Doc {
      get { return doc_; }
      set {
        doc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Reward" field.</summary>
    public const int RewardFieldNumber = 7;
    private string reward_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Reward {
      get { return reward_; }
      set {
        reward_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SystemId" field.</summary>
    public const int SystemIdFieldNumber = 8;
    private int systemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SystemId {
      get { return systemId_; }
      set {
        systemId_ = value;
      }
    }

    /// <summary>Field number for the "NameNote" field.</summary>
    public const int NameNoteFieldNumber = 9;
    private string nameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameNote {
      get { return nameNote_; }
      set {
        nameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DocNote" field.</summary>
    public const int DocNoteFieldNumber = 10;
    private string docNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DocNote {
      get { return docNote_; }
      set {
        docNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Conduct" field.</summary>
    public const int ConductFieldNumber = 11;
    private int conduct_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Conduct {
      get { return conduct_; }
      set {
        conduct_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigEventTaskUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigEventTaskUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Type != other.Type) return false;
      if (Param != other.Param) return false;
      if (Rate != other.Rate) return false;
      if (Name != other.Name) return false;
      if (Doc != other.Doc) return false;
      if (Reward != other.Reward) return false;
      if (SystemId != other.SystemId) return false;
      if (NameNote != other.NameNote) return false;
      if (DocNote != other.DocNote) return false;
      if (Conduct != other.Conduct) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Param.Length != 0) hash ^= Param.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Doc.Length != 0) hash ^= Doc.GetHashCode();
      if (Reward.Length != 0) hash ^= Reward.GetHashCode();
      if (SystemId != 0) hash ^= SystemId.GetHashCode();
      if (NameNote.Length != 0) hash ^= NameNote.GetHashCode();
      if (DocNote.Length != 0) hash ^= DocNote.GetHashCode();
      if (Conduct != 0) hash ^= Conduct.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (Param.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param);
      }
      if (Rate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Rate);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (Doc.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Doc);
      }
      if (Reward.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Reward);
      }
      if (SystemId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(SystemId);
      }
      if (NameNote.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(NameNote);
      }
      if (DocNote.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DocNote);
      }
      if (Conduct != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Conduct);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Param.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Doc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Doc);
      }
      if (Reward.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reward);
      }
      if (SystemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SystemId);
      }
      if (NameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNote);
      }
      if (DocNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DocNote);
      }
      if (Conduct != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Conduct);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigEventTaskUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Param.Length != 0) {
        Param = other.Param;
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Doc.Length != 0) {
        Doc = other.Doc;
      }
      if (other.Reward.Length != 0) {
        Reward = other.Reward;
      }
      if (other.SystemId != 0) {
        SystemId = other.SystemId;
      }
      if (other.NameNote.Length != 0) {
        NameNote = other.NameNote;
      }
      if (other.DocNote.Length != 0) {
        DocNote = other.DocNote;
      }
      if (other.Conduct != 0) {
        Conduct = other.Conduct;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
          case 26: {
            Param = input.ReadString();
            break;
          }
          case 32: {
            Rate = input.ReadInt32();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 50: {
            Doc = input.ReadString();
            break;
          }
          case 58: {
            Reward = input.ReadString();
            break;
          }
          case 64: {
            SystemId = input.ReadInt32();
            break;
          }
          case 74: {
            NameNote = input.ReadString();
            break;
          }
          case 82: {
            DocNote = input.ReadString();
            break;
          }
          case 88: {
            Conduct = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
