// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigRaffleLevelUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigRaffleLevelUnit.proto</summary>
  public static partial class ConfigRaffleLevelUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigRaffleLevelUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigRaffleLevelUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtDb25maWdSYWZmbGVMZXZlbFVuaXQucHJvdG8SBkNvbmZpZyLgAQoVQ29u",
            "ZmlnUmFmZmxlTGV2ZWxVbml0EgoKAklkGAEgASgFEgwKBFR5cGUYAiABKAUS",
            "DQoFTGV2ZWwYAyABKAUSEwoLUXVhbGl0eTFQcm8YBCABKAkSEwoLUXVhbGl0",
            "eTJQcm8YBSABKAkSEwoLUXVhbGl0eTNQcm8YBiABKAkSEwoLUXVhbGl0eTRQ",
            "cm8YByABKAkSEwoLUXVhbGl0eTVQcm8YCCABKAkSEwoLUXVhbGl0eTZQcm8Y",
            "CSABKAkSEwoLUXVhbGl0eTdQcm8YCiABKAkSCwoDRXhwGAsgASgFYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigRaffleLevelUnit), global::Config.ConfigRaffleLevelUnit.Parser, new[]{ "Id", "Type", "Level", "Quality1Pro", "Quality2Pro", "Quality3Pro", "Quality4Pro", "Quality5Pro", "Quality6Pro", "Quality7Pro", "Exp" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigRaffleLevelUnit : pb::IMessage<ConfigRaffleLevelUnit> {
    private static readonly pb::MessageParser<ConfigRaffleLevelUnit> _parser = new pb::MessageParser<ConfigRaffleLevelUnit>(() => new ConfigRaffleLevelUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigRaffleLevelUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigRaffleLevelUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigRaffleLevelUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigRaffleLevelUnit(ConfigRaffleLevelUnit other) : this() {
      id_ = other.id_;
      type_ = other.type_;
      level_ = other.level_;
      quality1Pro_ = other.quality1Pro_;
      quality2Pro_ = other.quality2Pro_;
      quality3Pro_ = other.quality3Pro_;
      quality4Pro_ = other.quality4Pro_;
      quality5Pro_ = other.quality5Pro_;
      quality6Pro_ = other.quality6Pro_;
      quality7Pro_ = other.quality7Pro_;
      exp_ = other.exp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigRaffleLevelUnit Clone() {
      return new ConfigRaffleLevelUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 3;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "Quality1Pro" field.</summary>
    public const int Quality1ProFieldNumber = 4;
    private string quality1Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality1Pro {
      get { return quality1Pro_; }
      set {
        quality1Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quality2Pro" field.</summary>
    public const int Quality2ProFieldNumber = 5;
    private string quality2Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality2Pro {
      get { return quality2Pro_; }
      set {
        quality2Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quality3Pro" field.</summary>
    public const int Quality3ProFieldNumber = 6;
    private string quality3Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality3Pro {
      get { return quality3Pro_; }
      set {
        quality3Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quality4Pro" field.</summary>
    public const int Quality4ProFieldNumber = 7;
    private string quality4Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality4Pro {
      get { return quality4Pro_; }
      set {
        quality4Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quality5Pro" field.</summary>
    public const int Quality5ProFieldNumber = 8;
    private string quality5Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality5Pro {
      get { return quality5Pro_; }
      set {
        quality5Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quality6Pro" field.</summary>
    public const int Quality6ProFieldNumber = 9;
    private string quality6Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality6Pro {
      get { return quality6Pro_; }
      set {
        quality6Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quality7Pro" field.</summary>
    public const int Quality7ProFieldNumber = 10;
    private string quality7Pro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quality7Pro {
      get { return quality7Pro_; }
      set {
        quality7Pro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Exp" field.</summary>
    public const int ExpFieldNumber = 11;
    private int exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigRaffleLevelUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigRaffleLevelUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Type != other.Type) return false;
      if (Level != other.Level) return false;
      if (Quality1Pro != other.Quality1Pro) return false;
      if (Quality2Pro != other.Quality2Pro) return false;
      if (Quality3Pro != other.Quality3Pro) return false;
      if (Quality4Pro != other.Quality4Pro) return false;
      if (Quality5Pro != other.Quality5Pro) return false;
      if (Quality6Pro != other.Quality6Pro) return false;
      if (Quality7Pro != other.Quality7Pro) return false;
      if (Exp != other.Exp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Quality1Pro.Length != 0) hash ^= Quality1Pro.GetHashCode();
      if (Quality2Pro.Length != 0) hash ^= Quality2Pro.GetHashCode();
      if (Quality3Pro.Length != 0) hash ^= Quality3Pro.GetHashCode();
      if (Quality4Pro.Length != 0) hash ^= Quality4Pro.GetHashCode();
      if (Quality5Pro.Length != 0) hash ^= Quality5Pro.GetHashCode();
      if (Quality6Pro.Length != 0) hash ^= Quality6Pro.GetHashCode();
      if (Quality7Pro.Length != 0) hash ^= Quality7Pro.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      if (Quality1Pro.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Quality1Pro);
      }
      if (Quality2Pro.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Quality2Pro);
      }
      if (Quality3Pro.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Quality3Pro);
      }
      if (Quality4Pro.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Quality4Pro);
      }
      if (Quality5Pro.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Quality5Pro);
      }
      if (Quality6Pro.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Quality6Pro);
      }
      if (Quality7Pro.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Quality7Pro);
      }
      if (Exp != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Exp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Quality1Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality1Pro);
      }
      if (Quality2Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality2Pro);
      }
      if (Quality3Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality3Pro);
      }
      if (Quality4Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality4Pro);
      }
      if (Quality5Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality5Pro);
      }
      if (Quality6Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality6Pro);
      }
      if (Quality7Pro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality7Pro);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigRaffleLevelUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Quality1Pro.Length != 0) {
        Quality1Pro = other.Quality1Pro;
      }
      if (other.Quality2Pro.Length != 0) {
        Quality2Pro = other.Quality2Pro;
      }
      if (other.Quality3Pro.Length != 0) {
        Quality3Pro = other.Quality3Pro;
      }
      if (other.Quality4Pro.Length != 0) {
        Quality4Pro = other.Quality4Pro;
      }
      if (other.Quality5Pro.Length != 0) {
        Quality5Pro = other.Quality5Pro;
      }
      if (other.Quality6Pro.Length != 0) {
        Quality6Pro = other.Quality6Pro;
      }
      if (other.Quality7Pro.Length != 0) {
        Quality7Pro = other.Quality7Pro;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
          case 34: {
            Quality1Pro = input.ReadString();
            break;
          }
          case 42: {
            Quality2Pro = input.ReadString();
            break;
          }
          case 50: {
            Quality3Pro = input.ReadString();
            break;
          }
          case 58: {
            Quality4Pro = input.ReadString();
            break;
          }
          case 66: {
            Quality5Pro = input.ReadString();
            break;
          }
          case 74: {
            Quality6Pro = input.ReadString();
            break;
          }
          case 82: {
            Quality7Pro = input.ReadString();
            break;
          }
          case 88: {
            Exp = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
