// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigSystemUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigSystemUnit.proto</summary>
  public static partial class ConfigSystemUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigSystemUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigSystemUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZDb25maWdTeXN0ZW1Vbml0LnByb3RvEgZDb25maWci3AEKEENvbmZpZ1N5",
            "c3RlbVVuaXQSCgoCSWQYASABKAUSEAoITmFtZU5vdGUYAiABKAkSDAoETmFt",
            "ZRgDIAEoCRIRCglOYW1lUGFyYW0YBCABKAkSFQoNQ29uZGl0aW9uVHlwZRgF",
            "IAEoBRIRCglDb25kaXRpb24YBiABKAkSEAoIRGVzY05vdGUYByABKAkSDAoE",
            "RGVzYxgIIAEoCRIRCglEZXNjUGFyYW0YCSABKAkSDAoESWNvbhgKIAEoBRIQ",
            "CghQb3NpdGlvbhgLIAEoBRIMCgRTaG93GAwgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigSystemUnit), global::Config.ConfigSystemUnit.Parser, new[]{ "Id", "NameNote", "Name", "NameParam", "ConditionType", "Condition", "DescNote", "Desc", "DescParam", "Icon", "Position", "Show" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigSystemUnit : pb::IMessage<ConfigSystemUnit> {
    private static readonly pb::MessageParser<ConfigSystemUnit> _parser = new pb::MessageParser<ConfigSystemUnit>(() => new ConfigSystemUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigSystemUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigSystemUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigSystemUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigSystemUnit(ConfigSystemUnit other) : this() {
      id_ = other.id_;
      nameNote_ = other.nameNote_;
      name_ = other.name_;
      nameParam_ = other.nameParam_;
      conditionType_ = other.conditionType_;
      condition_ = other.condition_;
      descNote_ = other.descNote_;
      desc_ = other.desc_;
      descParam_ = other.descParam_;
      icon_ = other.icon_;
      position_ = other.position_;
      show_ = other.show_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigSystemUnit Clone() {
      return new ConfigSystemUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "NameNote" field.</summary>
    public const int NameNoteFieldNumber = 2;
    private string nameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameNote {
      get { return nameNote_; }
      set {
        nameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NameParam" field.</summary>
    public const int NameParamFieldNumber = 4;
    private string nameParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameParam {
      get { return nameParam_; }
      set {
        nameParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ConditionType" field.</summary>
    public const int ConditionTypeFieldNumber = 5;
    private int conditionType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConditionType {
      get { return conditionType_; }
      set {
        conditionType_ = value;
      }
    }

    /// <summary>Field number for the "Condition" field.</summary>
    public const int ConditionFieldNumber = 6;
    private string condition_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Condition {
      get { return condition_; }
      set {
        condition_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DescNote" field.</summary>
    public const int DescNoteFieldNumber = 7;
    private string descNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DescNote {
      get { return descNote_; }
      set {
        descNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 8;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DescParam" field.</summary>
    public const int DescParamFieldNumber = 9;
    private string descParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DescParam {
      get { return descParam_; }
      set {
        descParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Icon" field.</summary>
    public const int IconFieldNumber = 10;
    private int icon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Icon {
      get { return icon_; }
      set {
        icon_ = value;
      }
    }

    /// <summary>Field number for the "Position" field.</summary>
    public const int PositionFieldNumber = 11;
    private int position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "Show" field.</summary>
    public const int ShowFieldNumber = 12;
    private int show_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Show {
      get { return show_; }
      set {
        show_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigSystemUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigSystemUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NameNote != other.NameNote) return false;
      if (Name != other.Name) return false;
      if (NameParam != other.NameParam) return false;
      if (ConditionType != other.ConditionType) return false;
      if (Condition != other.Condition) return false;
      if (DescNote != other.DescNote) return false;
      if (Desc != other.Desc) return false;
      if (DescParam != other.DescParam) return false;
      if (Icon != other.Icon) return false;
      if (Position != other.Position) return false;
      if (Show != other.Show) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (NameNote.Length != 0) hash ^= NameNote.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (NameParam.Length != 0) hash ^= NameParam.GetHashCode();
      if (ConditionType != 0) hash ^= ConditionType.GetHashCode();
      if (Condition.Length != 0) hash ^= Condition.GetHashCode();
      if (DescNote.Length != 0) hash ^= DescNote.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (DescParam.Length != 0) hash ^= DescParam.GetHashCode();
      if (Icon != 0) hash ^= Icon.GetHashCode();
      if (Position != 0) hash ^= Position.GetHashCode();
      if (Show != 0) hash ^= Show.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (NameNote.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameNote);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameParam.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameParam);
      }
      if (ConditionType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ConditionType);
      }
      if (Condition.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Condition);
      }
      if (DescNote.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DescNote);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Desc);
      }
      if (DescParam.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DescParam);
      }
      if (Icon != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Icon);
      }
      if (Position != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Position);
      }
      if (Show != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Show);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (NameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNote);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (NameParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameParam);
      }
      if (ConditionType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConditionType);
      }
      if (Condition.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Condition);
      }
      if (DescNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DescNote);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (DescParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DescParam);
      }
      if (Icon != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Icon);
      }
      if (Position != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Position);
      }
      if (Show != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Show);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigSystemUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.NameNote.Length != 0) {
        NameNote = other.NameNote;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.NameParam.Length != 0) {
        NameParam = other.NameParam;
      }
      if (other.ConditionType != 0) {
        ConditionType = other.ConditionType;
      }
      if (other.Condition.Length != 0) {
        Condition = other.Condition;
      }
      if (other.DescNote.Length != 0) {
        DescNote = other.DescNote;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.DescParam.Length != 0) {
        DescParam = other.DescParam;
      }
      if (other.Icon != 0) {
        Icon = other.Icon;
      }
      if (other.Position != 0) {
        Position = other.Position;
      }
      if (other.Show != 0) {
        Show = other.Show;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            NameNote = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameParam = input.ReadString();
            break;
          }
          case 40: {
            ConditionType = input.ReadInt32();
            break;
          }
          case 50: {
            Condition = input.ReadString();
            break;
          }
          case 58: {
            DescNote = input.ReadString();
            break;
          }
          case 66: {
            Desc = input.ReadString();
            break;
          }
          case 74: {
            DescParam = input.ReadString();
            break;
          }
          case 80: {
            Icon = input.ReadInt32();
            break;
          }
          case 88: {
            Position = input.ReadInt32();
            break;
          }
          case 96: {
            Show = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
