// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigPetHoleUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigPetHoleUnit.proto</summary>
  public static partial class ConfigPetHoleUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigPetHoleUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigPetHoleUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDb25maWdQZXRIb2xlVW5pdC5wcm90bxIGQ29uZmlnIpgBChFDb25maWdQ",
            "ZXRIb2xlVW5pdBIKCgJJZBgBIAEoBRIPCgdRdWFsaXR5GAIgASgFEg0KBUhv",
            "bGUxGAMgASgFEg0KBUhvbGUyGAQgASgFEg0KBUhvbGUzGAUgASgFEg0KBUJv",
            "b2sxGAYgASgFEg0KBUJvb2syGAcgASgFEg0KBUJvb2szGAggASgFEgwKBFR5",
            "cGUYCSABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigPetHoleUnit), global::Config.ConfigPetHoleUnit.Parser, new[]{ "Id", "Quality", "Hole1", "Hole2", "Hole3", "Book1", "Book2", "Book3", "Type" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigPetHoleUnit : pb::IMessage<ConfigPetHoleUnit> {
    private static readonly pb::MessageParser<ConfigPetHoleUnit> _parser = new pb::MessageParser<ConfigPetHoleUnit>(() => new ConfigPetHoleUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigPetHoleUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigPetHoleUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetHoleUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetHoleUnit(ConfigPetHoleUnit other) : this() {
      id_ = other.id_;
      quality_ = other.quality_;
      hole1_ = other.hole1_;
      hole2_ = other.hole2_;
      hole3_ = other.hole3_;
      book1_ = other.book1_;
      book2_ = other.book2_;
      book3_ = other.book3_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetHoleUnit Clone() {
      return new ConfigPetHoleUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Quality" field.</summary>
    public const int QualityFieldNumber = 2;
    private int quality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "Hole1" field.</summary>
    public const int Hole1FieldNumber = 3;
    private int hole1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hole1 {
      get { return hole1_; }
      set {
        hole1_ = value;
      }
    }

    /// <summary>Field number for the "Hole2" field.</summary>
    public const int Hole2FieldNumber = 4;
    private int hole2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hole2 {
      get { return hole2_; }
      set {
        hole2_ = value;
      }
    }

    /// <summary>Field number for the "Hole3" field.</summary>
    public const int Hole3FieldNumber = 5;
    private int hole3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hole3 {
      get { return hole3_; }
      set {
        hole3_ = value;
      }
    }

    /// <summary>Field number for the "Book1" field.</summary>
    public const int Book1FieldNumber = 6;
    private int book1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Book1 {
      get { return book1_; }
      set {
        book1_ = value;
      }
    }

    /// <summary>Field number for the "Book2" field.</summary>
    public const int Book2FieldNumber = 7;
    private int book2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Book2 {
      get { return book2_; }
      set {
        book2_ = value;
      }
    }

    /// <summary>Field number for the "Book3" field.</summary>
    public const int Book3FieldNumber = 8;
    private int book3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Book3 {
      get { return book3_; }
      set {
        book3_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 9;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigPetHoleUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigPetHoleUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Quality != other.Quality) return false;
      if (Hole1 != other.Hole1) return false;
      if (Hole2 != other.Hole2) return false;
      if (Hole3 != other.Hole3) return false;
      if (Book1 != other.Book1) return false;
      if (Book2 != other.Book2) return false;
      if (Book3 != other.Book3) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Quality != 0) hash ^= Quality.GetHashCode();
      if (Hole1 != 0) hash ^= Hole1.GetHashCode();
      if (Hole2 != 0) hash ^= Hole2.GetHashCode();
      if (Hole3 != 0) hash ^= Hole3.GetHashCode();
      if (Book1 != 0) hash ^= Book1.GetHashCode();
      if (Book2 != 0) hash ^= Book2.GetHashCode();
      if (Book3 != 0) hash ^= Book3.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Quality != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quality);
      }
      if (Hole1 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Hole1);
      }
      if (Hole2 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Hole2);
      }
      if (Hole3 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Hole3);
      }
      if (Book1 != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Book1);
      }
      if (Book2 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Book2);
      }
      if (Book3 != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Book3);
      }
      if (Type != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
      }
      if (Hole1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hole1);
      }
      if (Hole2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hole2);
      }
      if (Hole3 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hole3);
      }
      if (Book1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Book1);
      }
      if (Book2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Book2);
      }
      if (Book3 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Book3);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigPetHoleUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Quality != 0) {
        Quality = other.Quality;
      }
      if (other.Hole1 != 0) {
        Hole1 = other.Hole1;
      }
      if (other.Hole2 != 0) {
        Hole2 = other.Hole2;
      }
      if (other.Hole3 != 0) {
        Hole3 = other.Hole3;
      }
      if (other.Book1 != 0) {
        Book1 = other.Book1;
      }
      if (other.Book2 != 0) {
        Book2 = other.Book2;
      }
      if (other.Book3 != 0) {
        Book3 = other.Book3;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Quality = input.ReadInt32();
            break;
          }
          case 24: {
            Hole1 = input.ReadInt32();
            break;
          }
          case 32: {
            Hole2 = input.ReadInt32();
            break;
          }
          case 40: {
            Hole3 = input.ReadInt32();
            break;
          }
          case 48: {
            Book1 = input.ReadInt32();
            break;
          }
          case 56: {
            Book2 = input.ReadInt32();
            break;
          }
          case 64: {
            Book3 = input.ReadInt32();
            break;
          }
          case 72: {
            Type = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
