// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigPetSkillGroupUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigPetSkillGroupUnit.proto</summary>
  public static partial class ConfigPetSkillGroupUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigPetSkillGroupUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigPetSkillGroupUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Db25maWdQZXRTa2lsbEdyb3VwVW5pdC5wcm90bxIGQ29uZmlnIqgBChdD",
            "b25maWdQZXRTa2lsbEdyb3VwVW5pdBIKCgJJZBgBIAEoBRIPCgdRdWFsaXR5",
            "GAIgASgFEgwKBFR5cGUYAyABKAUSDQoFR3JvdXAYBCABKAUSDwoHU2tpbGxJ",
            "ZBgFIAEoBRIMCgRSYXRlGAYgASgFEgwKBEl0ZW0YByABKAUSEQoJTm90ZXNO",
            "YW1lGAggASgJEhMKC05vdGVzQ29tbW9uGAkgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigPetSkillGroupUnit), global::Config.ConfigPetSkillGroupUnit.Parser, new[]{ "Id", "Quality", "Type", "Group", "SkillId", "Rate", "Item", "NotesName", "NotesCommon" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigPetSkillGroupUnit : pb::IMessage<ConfigPetSkillGroupUnit> {
    private static readonly pb::MessageParser<ConfigPetSkillGroupUnit> _parser = new pb::MessageParser<ConfigPetSkillGroupUnit>(() => new ConfigPetSkillGroupUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigPetSkillGroupUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigPetSkillGroupUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetSkillGroupUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetSkillGroupUnit(ConfigPetSkillGroupUnit other) : this() {
      id_ = other.id_;
      quality_ = other.quality_;
      type_ = other.type_;
      group_ = other.group_;
      skillId_ = other.skillId_;
      rate_ = other.rate_;
      item_ = other.item_;
      notesName_ = other.notesName_;
      notesCommon_ = other.notesCommon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPetSkillGroupUnit Clone() {
      return new ConfigPetSkillGroupUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Quality" field.</summary>
    public const int QualityFieldNumber = 2;
    private int quality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 3;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Group" field.</summary>
    public const int GroupFieldNumber = 4;
    private int group_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Group {
      get { return group_; }
      set {
        group_ = value;
      }
    }

    /// <summary>Field number for the "SkillId" field.</summary>
    public const int SkillIdFieldNumber = 5;
    private int skillId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    /// <summary>Field number for the "Rate" field.</summary>
    public const int RateFieldNumber = 6;
    private int rate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "Item" field.</summary>
    public const int ItemFieldNumber = 7;
    private int item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "NotesName" field.</summary>
    public const int NotesNameFieldNumber = 8;
    private string notesName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NotesName {
      get { return notesName_; }
      set {
        notesName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NotesCommon" field.</summary>
    public const int NotesCommonFieldNumber = 9;
    private string notesCommon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NotesCommon {
      get { return notesCommon_; }
      set {
        notesCommon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigPetSkillGroupUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigPetSkillGroupUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Quality != other.Quality) return false;
      if (Type != other.Type) return false;
      if (Group != other.Group) return false;
      if (SkillId != other.SkillId) return false;
      if (Rate != other.Rate) return false;
      if (Item != other.Item) return false;
      if (NotesName != other.NotesName) return false;
      if (NotesCommon != other.NotesCommon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Quality != 0) hash ^= Quality.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Group != 0) hash ^= Group.GetHashCode();
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (Item != 0) hash ^= Item.GetHashCode();
      if (NotesName.Length != 0) hash ^= NotesName.GetHashCode();
      if (NotesCommon.Length != 0) hash ^= NotesCommon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Quality != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quality);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Type);
      }
      if (Group != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Group);
      }
      if (SkillId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SkillId);
      }
      if (Rate != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Rate);
      }
      if (Item != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Item);
      }
      if (NotesName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(NotesName);
      }
      if (NotesCommon.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(NotesCommon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Group != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Group);
      }
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillId);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (Item != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Item);
      }
      if (NotesName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NotesName);
      }
      if (NotesCommon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NotesCommon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigPetSkillGroupUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Quality != 0) {
        Quality = other.Quality;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Group != 0) {
        Group = other.Group;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      if (other.Item != 0) {
        Item = other.Item;
      }
      if (other.NotesName.Length != 0) {
        NotesName = other.NotesName;
      }
      if (other.NotesCommon.Length != 0) {
        NotesCommon = other.NotesCommon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Quality = input.ReadInt32();
            break;
          }
          case 24: {
            Type = input.ReadInt32();
            break;
          }
          case 32: {
            Group = input.ReadInt32();
            break;
          }
          case 40: {
            SkillId = input.ReadInt32();
            break;
          }
          case 48: {
            Rate = input.ReadInt32();
            break;
          }
          case 56: {
            Item = input.ReadInt32();
            break;
          }
          case 66: {
            NotesName = input.ReadString();
            break;
          }
          case 74: {
            NotesCommon = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
