// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigVipUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigVipUnit.proto</summary>
  public static partial class ConfigVipUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigVipUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigVipUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNDb25maWdWaXBVbml0LnByb3RvEgZDb25maWci2QEKDUNvbmZpZ1ZpcFVu",
            "aXQSCgoCSWQYASABKAUSDQoFTGV2ZWwYAiABKAUSEAoIRGlzY291bnQYAyAB",
            "KAUSDwoHUmVtYXJrcxgEIAEoCRIMCgREZXNjGAUgASgJEg4KBlZpcEV4cBgG",
            "IAEoBRISCgpWaXBFZWNlaXZlGAcgASgJEhMKC1ZpcFB1cmNoYXNlGAggASgJ",
            "Eg0KBVByaWNlGAkgAygFEhIKCkJhY2tncm91bmQYCiABKAkSEAoIVmlwQm9u",
            "dXMYCyABKAkSDgoGUmV3YXJkGAwgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigVipUnit), global::Config.ConfigVipUnit.Parser, new[]{ "Id", "Level", "Discount", "Remarks", "Desc", "VipExp", "VipEeceive", "VipPurchase", "Price", "Background", "VipBonus", "Reward" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigVipUnit : pb::IMessage<ConfigVipUnit> {
    private static readonly pb::MessageParser<ConfigVipUnit> _parser = new pb::MessageParser<ConfigVipUnit>(() => new ConfigVipUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigVipUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigVipUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigVipUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigVipUnit(ConfigVipUnit other) : this() {
      id_ = other.id_;
      level_ = other.level_;
      discount_ = other.discount_;
      remarks_ = other.remarks_;
      desc_ = other.desc_;
      vipExp_ = other.vipExp_;
      vipEeceive_ = other.vipEeceive_;
      vipPurchase_ = other.vipPurchase_;
      price_ = other.price_.Clone();
      background_ = other.background_;
      vipBonus_ = other.vipBonus_;
      reward_ = other.reward_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigVipUnit Clone() {
      return new ConfigVipUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "Discount" field.</summary>
    public const int DiscountFieldNumber = 3;
    private int discount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Discount {
      get { return discount_; }
      set {
        discount_ = value;
      }
    }

    /// <summary>Field number for the "Remarks" field.</summary>
    public const int RemarksFieldNumber = 4;
    private string remarks_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Remarks {
      get { return remarks_; }
      set {
        remarks_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 5;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VipExp" field.</summary>
    public const int VipExpFieldNumber = 6;
    private int vipExp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int VipExp {
      get { return vipExp_; }
      set {
        vipExp_ = value;
      }
    }

    /// <summary>Field number for the "VipEeceive" field.</summary>
    public const int VipEeceiveFieldNumber = 7;
    private string vipEeceive_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string VipEeceive {
      get { return vipEeceive_; }
      set {
        vipEeceive_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VipPurchase" field.</summary>
    public const int VipPurchaseFieldNumber = 8;
    private string vipPurchase_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string VipPurchase {
      get { return vipPurchase_; }
      set {
        vipPurchase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 9;
    private static readonly pb::FieldCodec<int> _repeated_price_codec
        = pb::FieldCodec.ForInt32(74);
    private readonly pbc::RepeatedField<int> price_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Price {
      get { return price_; }
    }

    /// <summary>Field number for the "Background" field.</summary>
    public const int BackgroundFieldNumber = 10;
    private string background_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Background {
      get { return background_; }
      set {
        background_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VipBonus" field.</summary>
    public const int VipBonusFieldNumber = 11;
    private string vipBonus_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string VipBonus {
      get { return vipBonus_; }
      set {
        vipBonus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Reward" field.</summary>
    public const int RewardFieldNumber = 12;
    private int reward_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigVipUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigVipUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Level != other.Level) return false;
      if (Discount != other.Discount) return false;
      if (Remarks != other.Remarks) return false;
      if (Desc != other.Desc) return false;
      if (VipExp != other.VipExp) return false;
      if (VipEeceive != other.VipEeceive) return false;
      if (VipPurchase != other.VipPurchase) return false;
      if(!price_.Equals(other.price_)) return false;
      if (Background != other.Background) return false;
      if (VipBonus != other.VipBonus) return false;
      if (Reward != other.Reward) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Discount != 0) hash ^= Discount.GetHashCode();
      if (Remarks.Length != 0) hash ^= Remarks.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (VipExp != 0) hash ^= VipExp.GetHashCode();
      if (VipEeceive.Length != 0) hash ^= VipEeceive.GetHashCode();
      if (VipPurchase.Length != 0) hash ^= VipPurchase.GetHashCode();
      hash ^= price_.GetHashCode();
      if (Background.Length != 0) hash ^= Background.GetHashCode();
      if (VipBonus.Length != 0) hash ^= VipBonus.GetHashCode();
      if (Reward != 0) hash ^= Reward.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Discount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Discount);
      }
      if (Remarks.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Remarks);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Desc);
      }
      if (VipExp != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(VipExp);
      }
      if (VipEeceive.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(VipEeceive);
      }
      if (VipPurchase.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(VipPurchase);
      }
      price_.WriteTo(output, _repeated_price_codec);
      if (Background.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Background);
      }
      if (VipBonus.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(VipBonus);
      }
      if (Reward != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Reward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Discount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Discount);
      }
      if (Remarks.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Remarks);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (VipExp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VipExp);
      }
      if (VipEeceive.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VipEeceive);
      }
      if (VipPurchase.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VipPurchase);
      }
      size += price_.CalculateSize(_repeated_price_codec);
      if (Background.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Background);
      }
      if (VipBonus.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VipBonus);
      }
      if (Reward != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Reward);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigVipUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Discount != 0) {
        Discount = other.Discount;
      }
      if (other.Remarks.Length != 0) {
        Remarks = other.Remarks;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.VipExp != 0) {
        VipExp = other.VipExp;
      }
      if (other.VipEeceive.Length != 0) {
        VipEeceive = other.VipEeceive;
      }
      if (other.VipPurchase.Length != 0) {
        VipPurchase = other.VipPurchase;
      }
      price_.Add(other.price_);
      if (other.Background.Length != 0) {
        Background = other.Background;
      }
      if (other.VipBonus.Length != 0) {
        VipBonus = other.VipBonus;
      }
      if (other.Reward != 0) {
        Reward = other.Reward;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            Discount = input.ReadInt32();
            break;
          }
          case 34: {
            Remarks = input.ReadString();
            break;
          }
          case 42: {
            Desc = input.ReadString();
            break;
          }
          case 48: {
            VipExp = input.ReadInt32();
            break;
          }
          case 58: {
            VipEeceive = input.ReadString();
            break;
          }
          case 66: {
            VipPurchase = input.ReadString();
            break;
          }
          case 74:
          case 72: {
            price_.AddEntriesFrom(input, _repeated_price_codec);
            break;
          }
          case 82: {
            Background = input.ReadString();
            break;
          }
          case 90: {
            VipBonus = input.ReadString();
            break;
          }
          case 96: {
            Reward = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
