// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigRingUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigRingUnit.proto</summary>
  public static partial class ConfigRingUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigRingUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigRingUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb25maWdSaW5nVW5pdC5wcm90bxIGQ29uZmlnIpsBCg5Db25maWdSaW5n",
            "VW5pdBIKCgJJZBgBIAEoBRIRCglBdHRyTGV2ZWwYAiABKAUSCwoDQXRrGAMg",
            "ASgFEgoKAkhQGAQgASgFEhYKDkNyaXRpY2FsU3RyaWtlGAUgASgFEhYKDkNy",
            "aXRpY2FsSW5qdXJ5GAYgASgFEhAKCFJlY292ZXJ5GAcgASgFEg8KB0NvbnN1",
            "bWUYCCABKANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigRingUnit), global::Config.ConfigRingUnit.Parser, new[]{ "Id", "AttrLevel", "Atk", "HP", "CriticalStrike", "CriticalInjury", "Recovery", "Consume" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigRingUnit : pb::IMessage<ConfigRingUnit> {
    private static readonly pb::MessageParser<ConfigRingUnit> _parser = new pb::MessageParser<ConfigRingUnit>(() => new ConfigRingUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigRingUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigRingUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigRingUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigRingUnit(ConfigRingUnit other) : this() {
      id_ = other.id_;
      attrLevel_ = other.attrLevel_;
      atk_ = other.atk_;
      hP_ = other.hP_;
      criticalStrike_ = other.criticalStrike_;
      criticalInjury_ = other.criticalInjury_;
      recovery_ = other.recovery_;
      consume_ = other.consume_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigRingUnit Clone() {
      return new ConfigRingUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "AttrLevel" field.</summary>
    public const int AttrLevelFieldNumber = 2;
    private int attrLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AttrLevel {
      get { return attrLevel_; }
      set {
        attrLevel_ = value;
      }
    }

    /// <summary>Field number for the "Atk" field.</summary>
    public const int AtkFieldNumber = 3;
    private int atk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Atk {
      get { return atk_; }
      set {
        atk_ = value;
      }
    }

    /// <summary>Field number for the "HP" field.</summary>
    public const int HPFieldNumber = 4;
    private int hP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int HP {
      get { return hP_; }
      set {
        hP_ = value;
      }
    }

    /// <summary>Field number for the "CriticalStrike" field.</summary>
    public const int CriticalStrikeFieldNumber = 5;
    private int criticalStrike_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CriticalStrike {
      get { return criticalStrike_; }
      set {
        criticalStrike_ = value;
      }
    }

    /// <summary>Field number for the "CriticalInjury" field.</summary>
    public const int CriticalInjuryFieldNumber = 6;
    private int criticalInjury_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CriticalInjury {
      get { return criticalInjury_; }
      set {
        criticalInjury_ = value;
      }
    }

    /// <summary>Field number for the "Recovery" field.</summary>
    public const int RecoveryFieldNumber = 7;
    private int recovery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Recovery {
      get { return recovery_; }
      set {
        recovery_ = value;
      }
    }

    /// <summary>Field number for the "Consume" field.</summary>
    public const int ConsumeFieldNumber = 8;
    private long consume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Consume {
      get { return consume_; }
      set {
        consume_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigRingUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigRingUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (AttrLevel != other.AttrLevel) return false;
      if (Atk != other.Atk) return false;
      if (HP != other.HP) return false;
      if (CriticalStrike != other.CriticalStrike) return false;
      if (CriticalInjury != other.CriticalInjury) return false;
      if (Recovery != other.Recovery) return false;
      if (Consume != other.Consume) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (AttrLevel != 0) hash ^= AttrLevel.GetHashCode();
      if (Atk != 0) hash ^= Atk.GetHashCode();
      if (HP != 0) hash ^= HP.GetHashCode();
      if (CriticalStrike != 0) hash ^= CriticalStrike.GetHashCode();
      if (CriticalInjury != 0) hash ^= CriticalInjury.GetHashCode();
      if (Recovery != 0) hash ^= Recovery.GetHashCode();
      if (Consume != 0L) hash ^= Consume.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (AttrLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AttrLevel);
      }
      if (Atk != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Atk);
      }
      if (HP != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(HP);
      }
      if (CriticalStrike != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(CriticalStrike);
      }
      if (CriticalInjury != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CriticalInjury);
      }
      if (Recovery != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Recovery);
      }
      if (Consume != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Consume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (AttrLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttrLevel);
      }
      if (Atk != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Atk);
      }
      if (HP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HP);
      }
      if (CriticalStrike != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CriticalStrike);
      }
      if (CriticalInjury != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CriticalInjury);
      }
      if (Recovery != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Recovery);
      }
      if (Consume != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Consume);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigRingUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.AttrLevel != 0) {
        AttrLevel = other.AttrLevel;
      }
      if (other.Atk != 0) {
        Atk = other.Atk;
      }
      if (other.HP != 0) {
        HP = other.HP;
      }
      if (other.CriticalStrike != 0) {
        CriticalStrike = other.CriticalStrike;
      }
      if (other.CriticalInjury != 0) {
        CriticalInjury = other.CriticalInjury;
      }
      if (other.Recovery != 0) {
        Recovery = other.Recovery;
      }
      if (other.Consume != 0L) {
        Consume = other.Consume;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            AttrLevel = input.ReadInt32();
            break;
          }
          case 24: {
            Atk = input.ReadInt32();
            break;
          }
          case 32: {
            HP = input.ReadInt32();
            break;
          }
          case 40: {
            CriticalStrike = input.ReadInt32();
            break;
          }
          case 48: {
            CriticalInjury = input.ReadInt32();
            break;
          }
          case 56: {
            Recovery = input.ReadInt32();
            break;
          }
          case 64: {
            Consume = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
