// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigPassGiftUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigPassGiftUnit.proto</summary>
  public static partial class ConfigPassGiftUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigPassGiftUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigPassGiftUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDb25maWdQYXNzR2lmdFVuaXQucHJvdG8SBkNvbmZpZyJ1ChJDb25maWdQ",
            "YXNzR2lmdFVuaXQSCgoCSWQYASABKAUSDQoFTGV2ZWwYAiABKAUSDQoFU2Nv",
            "cmUYAyABKAUSDAoER2lmdBgEIAEoCRIRCglGYW5jeUdpZnQYBSABKAkSFAoM",
            "U3RhZ2VMZXZlbElkGAYgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigPassGiftUnit), global::Config.ConfigPassGiftUnit.Parser, new[]{ "Id", "Level", "Score", "Gift", "FancyGift", "StageLevelId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigPassGiftUnit : pb::IMessage<ConfigPassGiftUnit> {
    private static readonly pb::MessageParser<ConfigPassGiftUnit> _parser = new pb::MessageParser<ConfigPassGiftUnit>(() => new ConfigPassGiftUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigPassGiftUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigPassGiftUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPassGiftUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPassGiftUnit(ConfigPassGiftUnit other) : this() {
      id_ = other.id_;
      level_ = other.level_;
      score_ = other.score_;
      gift_ = other.gift_;
      fancyGift_ = other.fancyGift_;
      stageLevelId_ = other.stageLevelId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigPassGiftUnit Clone() {
      return new ConfigPassGiftUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "Score" field.</summary>
    public const int ScoreFieldNumber = 3;
    private int score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "Gift" field.</summary>
    public const int GiftFieldNumber = 4;
    private string gift_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Gift {
      get { return gift_; }
      set {
        gift_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FancyGift" field.</summary>
    public const int FancyGiftFieldNumber = 5;
    private string fancyGift_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FancyGift {
      get { return fancyGift_; }
      set {
        fancyGift_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "StageLevelId" field.</summary>
    public const int StageLevelIdFieldNumber = 6;
    private int stageLevelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StageLevelId {
      get { return stageLevelId_; }
      set {
        stageLevelId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigPassGiftUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigPassGiftUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Level != other.Level) return false;
      if (Score != other.Score) return false;
      if (Gift != other.Gift) return false;
      if (FancyGift != other.FancyGift) return false;
      if (StageLevelId != other.StageLevelId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      if (Gift.Length != 0) hash ^= Gift.GetHashCode();
      if (FancyGift.Length != 0) hash ^= FancyGift.GetHashCode();
      if (StageLevelId != 0) hash ^= StageLevelId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Score != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Score);
      }
      if (Gift.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gift);
      }
      if (FancyGift.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FancyGift);
      }
      if (StageLevelId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(StageLevelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
      }
      if (Gift.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gift);
      }
      if (FancyGift.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FancyGift);
      }
      if (StageLevelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StageLevelId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigPassGiftUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
      if (other.Gift.Length != 0) {
        Gift = other.Gift;
      }
      if (other.FancyGift.Length != 0) {
        FancyGift = other.FancyGift;
      }
      if (other.StageLevelId != 0) {
        StageLevelId = other.StageLevelId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            Score = input.ReadInt32();
            break;
          }
          case 34: {
            Gift = input.ReadString();
            break;
          }
          case 42: {
            FancyGift = input.ReadString();
            break;
          }
          case 48: {
            StageLevelId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
