// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigMultiLangUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigMultiLangUnit.proto</summary>
  public static partial class ConfigMultiLangUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigMultiLangUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigMultiLangUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDb25maWdNdWx0aUxhbmdVbml0LnByb3RvEgZDb25maWcigQEKE0NvbmZp",
            "Z011bHRpTGFuZ1VuaXQSCgoCSWQYASABKAkSCgoCQ04YAiABKAkSCgoCRU4Y",
            "AyABKAkSCgoCSlAYBCABKAkSCgoCS1IYBSABKAkSCgoCWkgYBiABKAkSDgoG",
            "UGFyYW1zGAcgASgFEhIKClBhcmFtT3JkZXIYCCABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigMultiLangUnit), global::Config.ConfigMultiLangUnit.Parser, new[]{ "Id", "CN", "EN", "JP", "KR", "ZH", "Params", "ParamOrder" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigMultiLangUnit : pb::IMessage<ConfigMultiLangUnit> {
    private static readonly pb::MessageParser<ConfigMultiLangUnit> _parser = new pb::MessageParser<ConfigMultiLangUnit>(() => new ConfigMultiLangUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigMultiLangUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigMultiLangUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMultiLangUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMultiLangUnit(ConfigMultiLangUnit other) : this() {
      id_ = other.id_;
      cN_ = other.cN_;
      eN_ = other.eN_;
      jP_ = other.jP_;
      kR_ = other.kR_;
      zH_ = other.zH_;
      params_ = other.params_;
      paramOrder_ = other.paramOrder_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMultiLangUnit Clone() {
      return new ConfigMultiLangUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CN" field.</summary>
    public const int CNFieldNumber = 2;
    private string cN_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CN {
      get { return cN_; }
      set {
        cN_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EN" field.</summary>
    public const int ENFieldNumber = 3;
    private string eN_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EN {
      get { return eN_; }
      set {
        eN_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "JP" field.</summary>
    public const int JPFieldNumber = 4;
    private string jP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JP {
      get { return jP_; }
      set {
        jP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "KR" field.</summary>
    public const int KRFieldNumber = 5;
    private string kR_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KR {
      get { return kR_; }
      set {
        kR_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ZH" field.</summary>
    public const int ZHFieldNumber = 6;
    private string zH_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ZH {
      get { return zH_; }
      set {
        zH_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Params" field.</summary>
    public const int ParamsFieldNumber = 7;
    private int params_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Params {
      get { return params_; }
      set {
        params_ = value;
      }
    }

    /// <summary>Field number for the "ParamOrder" field.</summary>
    public const int ParamOrderFieldNumber = 8;
    private string paramOrder_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ParamOrder {
      get { return paramOrder_; }
      set {
        paramOrder_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigMultiLangUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigMultiLangUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (CN != other.CN) return false;
      if (EN != other.EN) return false;
      if (JP != other.JP) return false;
      if (KR != other.KR) return false;
      if (ZH != other.ZH) return false;
      if (Params != other.Params) return false;
      if (ParamOrder != other.ParamOrder) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (CN.Length != 0) hash ^= CN.GetHashCode();
      if (EN.Length != 0) hash ^= EN.GetHashCode();
      if (JP.Length != 0) hash ^= JP.GetHashCode();
      if (KR.Length != 0) hash ^= KR.GetHashCode();
      if (ZH.Length != 0) hash ^= ZH.GetHashCode();
      if (Params != 0) hash ^= Params.GetHashCode();
      if (ParamOrder.Length != 0) hash ^= ParamOrder.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CN.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CN);
      }
      if (EN.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EN);
      }
      if (JP.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(JP);
      }
      if (KR.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(KR);
      }
      if (ZH.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ZH);
      }
      if (Params != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Params);
      }
      if (ParamOrder.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ParamOrder);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (CN.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CN);
      }
      if (EN.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EN);
      }
      if (JP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JP);
      }
      if (KR.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KR);
      }
      if (ZH.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ZH);
      }
      if (Params != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Params);
      }
      if (ParamOrder.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParamOrder);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigMultiLangUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.CN.Length != 0) {
        CN = other.CN;
      }
      if (other.EN.Length != 0) {
        EN = other.EN;
      }
      if (other.JP.Length != 0) {
        JP = other.JP;
      }
      if (other.KR.Length != 0) {
        KR = other.KR;
      }
      if (other.ZH.Length != 0) {
        ZH = other.ZH;
      }
      if (other.Params != 0) {
        Params = other.Params;
      }
      if (other.ParamOrder.Length != 0) {
        ParamOrder = other.ParamOrder;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CN = input.ReadString();
            break;
          }
          case 26: {
            EN = input.ReadString();
            break;
          }
          case 34: {
            JP = input.ReadString();
            break;
          }
          case 42: {
            KR = input.ReadString();
            break;
          }
          case 50: {
            ZH = input.ReadString();
            break;
          }
          case 56: {
            Params = input.ReadInt32();
            break;
          }
          case 66: {
            ParamOrder = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
