// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigMailUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigMailUnit.proto</summary>
  public static partial class ConfigMailUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigMailUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigMailUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb25maWdNYWlsVW5pdC5wcm90bxIGQ29uZmlnIvgBCg5Db25maWdNYWls",
            "VW5pdBIKCgJJZBgBIAEoBRIRCglUaXRsZU5vdGUYAiABKAkSDQoFVGl0bGUY",
            "AyABKAkSEgoKVGl0bGVQYXJhbRgEIAEoCRIPCgdUeHROb3RlGAUgASgJEgsK",
            "A1R4dBgGIAEoCRIQCghUeHRQYXJhbRgHIAEoCRIWCg5TZW5kZXJOYW1lTm90",
            "ZRgIIAEoCRISCgpTZW5kZXJOYW1lGAkgASgJEhAKCExpdmVUaW1lGAogASgF",
            "EhEKCVN0YXJ0VGltZRgLIAEoCRIPCgdFbmRUaW1lGAwgASgJEhIKCklzT25l",
            "Q2xpY2sYDSABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigMailUnit), global::Config.ConfigMailUnit.Parser, new[]{ "Id", "TitleNote", "Title", "TitleParam", "TxtNote", "Txt", "TxtParam", "SenderNameNote", "SenderName", "LiveTime", "StartTime", "EndTime", "IsOneClick" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigMailUnit : pb::IMessage<ConfigMailUnit> {
    private static readonly pb::MessageParser<ConfigMailUnit> _parser = new pb::MessageParser<ConfigMailUnit>(() => new ConfigMailUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigMailUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigMailUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMailUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMailUnit(ConfigMailUnit other) : this() {
      id_ = other.id_;
      titleNote_ = other.titleNote_;
      title_ = other.title_;
      titleParam_ = other.titleParam_;
      txtNote_ = other.txtNote_;
      txt_ = other.txt_;
      txtParam_ = other.txtParam_;
      senderNameNote_ = other.senderNameNote_;
      senderName_ = other.senderName_;
      liveTime_ = other.liveTime_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      isOneClick_ = other.isOneClick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMailUnit Clone() {
      return new ConfigMailUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "TitleNote" field.</summary>
    public const int TitleNoteFieldNumber = 2;
    private string titleNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TitleNote {
      get { return titleNote_; }
      set {
        titleNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 3;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TitleParam" field.</summary>
    public const int TitleParamFieldNumber = 4;
    private string titleParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TitleParam {
      get { return titleParam_; }
      set {
        titleParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TxtNote" field.</summary>
    public const int TxtNoteFieldNumber = 5;
    private string txtNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TxtNote {
      get { return txtNote_; }
      set {
        txtNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Txt" field.</summary>
    public const int TxtFieldNumber = 6;
    private string txt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Txt {
      get { return txt_; }
      set {
        txt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TxtParam" field.</summary>
    public const int TxtParamFieldNumber = 7;
    private string txtParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TxtParam {
      get { return txtParam_; }
      set {
        txtParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderNameNote" field.</summary>
    public const int SenderNameNoteFieldNumber = 8;
    private string senderNameNote_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SenderNameNote {
      get { return senderNameNote_; }
      set {
        senderNameNote_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderName" field.</summary>
    public const int SenderNameFieldNumber = 9;
    private string senderName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SenderName {
      get { return senderName_; }
      set {
        senderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LiveTime" field.</summary>
    public const int LiveTimeFieldNumber = 10;
    private int liveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LiveTime {
      get { return liveTime_; }
      set {
        liveTime_ = value;
      }
    }

    /// <summary>Field number for the "StartTime" field.</summary>
    public const int StartTimeFieldNumber = 11;
    private string startTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StartTime {
      get { return startTime_; }
      set {
        startTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EndTime" field.</summary>
    public const int EndTimeFieldNumber = 12;
    private string endTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EndTime {
      get { return endTime_; }
      set {
        endTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsOneClick" field.</summary>
    public const int IsOneClickFieldNumber = 13;
    private int isOneClick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IsOneClick {
      get { return isOneClick_; }
      set {
        isOneClick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigMailUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigMailUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (TitleNote != other.TitleNote) return false;
      if (Title != other.Title) return false;
      if (TitleParam != other.TitleParam) return false;
      if (TxtNote != other.TxtNote) return false;
      if (Txt != other.Txt) return false;
      if (TxtParam != other.TxtParam) return false;
      if (SenderNameNote != other.SenderNameNote) return false;
      if (SenderName != other.SenderName) return false;
      if (LiveTime != other.LiveTime) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (IsOneClick != other.IsOneClick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (TitleNote.Length != 0) hash ^= TitleNote.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (TitleParam.Length != 0) hash ^= TitleParam.GetHashCode();
      if (TxtNote.Length != 0) hash ^= TxtNote.GetHashCode();
      if (Txt.Length != 0) hash ^= Txt.GetHashCode();
      if (TxtParam.Length != 0) hash ^= TxtParam.GetHashCode();
      if (SenderNameNote.Length != 0) hash ^= SenderNameNote.GetHashCode();
      if (SenderName.Length != 0) hash ^= SenderName.GetHashCode();
      if (LiveTime != 0) hash ^= LiveTime.GetHashCode();
      if (StartTime.Length != 0) hash ^= StartTime.GetHashCode();
      if (EndTime.Length != 0) hash ^= EndTime.GetHashCode();
      if (IsOneClick != 0) hash ^= IsOneClick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (TitleNote.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TitleNote);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Title);
      }
      if (TitleParam.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TitleParam);
      }
      if (TxtNote.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TxtNote);
      }
      if (Txt.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Txt);
      }
      if (TxtParam.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(TxtParam);
      }
      if (SenderNameNote.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(SenderNameNote);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(SenderName);
      }
      if (LiveTime != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(LiveTime);
      }
      if (StartTime.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(StartTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(EndTime);
      }
      if (IsOneClick != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(IsOneClick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (TitleNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitleNote);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (TitleParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitleParam);
      }
      if (TxtNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TxtNote);
      }
      if (Txt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Txt);
      }
      if (TxtParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TxtParam);
      }
      if (SenderNameNote.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderNameNote);
      }
      if (SenderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderName);
      }
      if (LiveTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LiveTime);
      }
      if (StartTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartTime);
      }
      if (EndTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndTime);
      }
      if (IsOneClick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsOneClick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigMailUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.TitleNote.Length != 0) {
        TitleNote = other.TitleNote;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.TitleParam.Length != 0) {
        TitleParam = other.TitleParam;
      }
      if (other.TxtNote.Length != 0) {
        TxtNote = other.TxtNote;
      }
      if (other.Txt.Length != 0) {
        Txt = other.Txt;
      }
      if (other.TxtParam.Length != 0) {
        TxtParam = other.TxtParam;
      }
      if (other.SenderNameNote.Length != 0) {
        SenderNameNote = other.SenderNameNote;
      }
      if (other.SenderName.Length != 0) {
        SenderName = other.SenderName;
      }
      if (other.LiveTime != 0) {
        LiveTime = other.LiveTime;
      }
      if (other.StartTime.Length != 0) {
        StartTime = other.StartTime;
      }
      if (other.EndTime.Length != 0) {
        EndTime = other.EndTime;
      }
      if (other.IsOneClick != 0) {
        IsOneClick = other.IsOneClick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            TitleNote = input.ReadString();
            break;
          }
          case 26: {
            Title = input.ReadString();
            break;
          }
          case 34: {
            TitleParam = input.ReadString();
            break;
          }
          case 42: {
            TxtNote = input.ReadString();
            break;
          }
          case 50: {
            Txt = input.ReadString();
            break;
          }
          case 58: {
            TxtParam = input.ReadString();
            break;
          }
          case 66: {
            SenderNameNote = input.ReadString();
            break;
          }
          case 74: {
            SenderName = input.ReadString();
            break;
          }
          case 80: {
            LiveTime = input.ReadInt32();
            break;
          }
          case 90: {
            StartTime = input.ReadString();
            break;
          }
          case 98: {
            EndTime = input.ReadString();
            break;
          }
          case 104: {
            IsOneClick = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
