// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigTurntableLevelUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigTurntableLevelUnit.proto</summary>
  public static partial class ConfigTurntableLevelUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigTurntableLevelUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigTurntableLevelUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Db25maWdUdXJudGFibGVMZXZlbFVuaXQucHJvdG8SBkNvbmZpZyJ4ChhD",
            "b25maWdUdXJudGFibGVMZXZlbFVuaXQSCgoCSWQYASABKAUSDQoFTGV2ZWwY",
            "AiABKAUSCwoDRXhwGAMgASgFEg4KBlJld2FyZBgEIAEoCRIUCgxCb3hSZXdh",
            "cmRzSWQYBSADKAUSDgoGTnVtUmVxGAYgAygFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigTurntableLevelUnit), global::Config.ConfigTurntableLevelUnit.Parser, new[]{ "Id", "Level", "Exp", "Reward", "BoxRewardsId", "NumReq" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigTurntableLevelUnit : pb::IMessage<ConfigTurntableLevelUnit> {
    private static readonly pb::MessageParser<ConfigTurntableLevelUnit> _parser = new pb::MessageParser<ConfigTurntableLevelUnit>(() => new ConfigTurntableLevelUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigTurntableLevelUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigTurntableLevelUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTurntableLevelUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTurntableLevelUnit(ConfigTurntableLevelUnit other) : this() {
      id_ = other.id_;
      level_ = other.level_;
      exp_ = other.exp_;
      reward_ = other.reward_;
      boxRewardsId_ = other.boxRewardsId_.Clone();
      numReq_ = other.numReq_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTurntableLevelUnit Clone() {
      return new ConfigTurntableLevelUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "Exp" field.</summary>
    public const int ExpFieldNumber = 3;
    private int exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "Reward" field.</summary>
    public const int RewardFieldNumber = 4;
    private string reward_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Reward {
      get { return reward_; }
      set {
        reward_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BoxRewardsId" field.</summary>
    public const int BoxRewardsIdFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_boxRewardsId_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> boxRewardsId_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> BoxRewardsId {
      get { return boxRewardsId_; }
    }

    /// <summary>Field number for the "NumReq" field.</summary>
    public const int NumReqFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_numReq_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> numReq_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> NumReq {
      get { return numReq_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigTurntableLevelUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigTurntableLevelUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Level != other.Level) return false;
      if (Exp != other.Exp) return false;
      if (Reward != other.Reward) return false;
      if(!boxRewardsId_.Equals(other.boxRewardsId_)) return false;
      if(!numReq_.Equals(other.numReq_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (Reward.Length != 0) hash ^= Reward.GetHashCode();
      hash ^= boxRewardsId_.GetHashCode();
      hash ^= numReq_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Exp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Exp);
      }
      if (Reward.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Reward);
      }
      boxRewardsId_.WriteTo(output, _repeated_boxRewardsId_codec);
      numReq_.WriteTo(output, _repeated_numReq_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
      }
      if (Reward.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reward);
      }
      size += boxRewardsId_.CalculateSize(_repeated_boxRewardsId_codec);
      size += numReq_.CalculateSize(_repeated_numReq_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigTurntableLevelUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      if (other.Reward.Length != 0) {
        Reward = other.Reward;
      }
      boxRewardsId_.Add(other.boxRewardsId_);
      numReq_.Add(other.numReq_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            Exp = input.ReadInt32();
            break;
          }
          case 34: {
            Reward = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            boxRewardsId_.AddEntriesFrom(input, _repeated_boxRewardsId_codec);
            break;
          }
          case 50:
          case 48: {
            numReq_.AddEntriesFrom(input, _repeated_numReq_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
