// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigArtifactEquipUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigArtifactEquipUnit.proto</summary>
  public static partial class ConfigArtifactEquipUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigArtifactEquipUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigArtifactEquipUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Db25maWdBcnRpZmFjdEVxdWlwVW5pdC5wcm90bxIGQ29uZmlnIpABChdD",
            "b25maWdBcnRpZmFjdEVxdWlwVW5pdBIKCgJJZBgBIAEoBRIOCgZJdGVtSWQY",
            "AiABKAUSDAoEVHlwZRgDIAEoBRIVCg1BcnRpZmFjdExldmVsGAQgASgFEhQK",
            "DERpYW1vbmRzQ29zdBgFIAEoBRIQCghJdGVtQ29zdBgGIAEoCRIMCgRBdHRy",
            "GAcgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigArtifactEquipUnit), global::Config.ConfigArtifactEquipUnit.Parser, new[]{ "Id", "ItemId", "Type", "ArtifactLevel", "DiamondsCost", "ItemCost", "Attr" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigArtifactEquipUnit : pb::IMessage<ConfigArtifactEquipUnit> {
    private static readonly pb::MessageParser<ConfigArtifactEquipUnit> _parser = new pb::MessageParser<ConfigArtifactEquipUnit>(() => new ConfigArtifactEquipUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigArtifactEquipUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigArtifactEquipUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigArtifactEquipUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigArtifactEquipUnit(ConfigArtifactEquipUnit other) : this() {
      id_ = other.id_;
      itemId_ = other.itemId_;
      type_ = other.type_;
      artifactLevel_ = other.artifactLevel_;
      diamondsCost_ = other.diamondsCost_;
      itemCost_ = other.itemCost_;
      attr_ = other.attr_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigArtifactEquipUnit Clone() {
      return new ConfigArtifactEquipUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "ItemId" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 3;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "ArtifactLevel" field.</summary>
    public const int ArtifactLevelFieldNumber = 4;
    private int artifactLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ArtifactLevel {
      get { return artifactLevel_; }
      set {
        artifactLevel_ = value;
      }
    }

    /// <summary>Field number for the "DiamondsCost" field.</summary>
    public const int DiamondsCostFieldNumber = 5;
    private int diamondsCost_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DiamondsCost {
      get { return diamondsCost_; }
      set {
        diamondsCost_ = value;
      }
    }

    /// <summary>Field number for the "ItemCost" field.</summary>
    public const int ItemCostFieldNumber = 6;
    private string itemCost_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemCost {
      get { return itemCost_; }
      set {
        itemCost_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Attr" field.</summary>
    public const int AttrFieldNumber = 7;
    private string attr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Attr {
      get { return attr_; }
      set {
        attr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigArtifactEquipUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigArtifactEquipUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ItemId != other.ItemId) return false;
      if (Type != other.Type) return false;
      if (ArtifactLevel != other.ArtifactLevel) return false;
      if (DiamondsCost != other.DiamondsCost) return false;
      if (ItemCost != other.ItemCost) return false;
      if (Attr != other.Attr) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (ItemId != 0) hash ^= ItemId.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (ArtifactLevel != 0) hash ^= ArtifactLevel.GetHashCode();
      if (DiamondsCost != 0) hash ^= DiamondsCost.GetHashCode();
      if (ItemCost.Length != 0) hash ^= ItemCost.GetHashCode();
      if (Attr.Length != 0) hash ^= Attr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Type);
      }
      if (ArtifactLevel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ArtifactLevel);
      }
      if (DiamondsCost != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DiamondsCost);
      }
      if (ItemCost.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ItemCost);
      }
      if (Attr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Attr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (ArtifactLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ArtifactLevel);
      }
      if (DiamondsCost != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DiamondsCost);
      }
      if (ItemCost.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemCost);
      }
      if (Attr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Attr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigArtifactEquipUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.ItemId != 0) {
        ItemId = other.ItemId;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.ArtifactLevel != 0) {
        ArtifactLevel = other.ArtifactLevel;
      }
      if (other.DiamondsCost != 0) {
        DiamondsCost = other.DiamondsCost;
      }
      if (other.ItemCost.Length != 0) {
        ItemCost = other.ItemCost;
      }
      if (other.Attr.Length != 0) {
        Attr = other.Attr;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            Type = input.ReadInt32();
            break;
          }
          case 32: {
            ArtifactLevel = input.ReadInt32();
            break;
          }
          case 40: {
            DiamondsCost = input.ReadInt32();
            break;
          }
          case 50: {
            ItemCost = input.ReadString();
            break;
          }
          case 58: {
            Attr = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
