// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigLoreEntryQualityUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from ConfigLoreEntryQualityUnit.proto</summary>
  public static partial class ConfigLoreEntryQualityUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigLoreEntryQualityUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigLoreEntryQualityUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBDb25maWdMb3JlRW50cnlRdWFsaXR5VW5pdC5wcm90bxIGQ29uZmlnImoK",
            "GkNvbmZpZ0xvcmVFbnRyeVF1YWxpdHlVbml0EgoKAklkGAEgASgFEg8KB1F1",
            "YWxpdHkYAiABKAUSDAoEUmF0ZRgDIAEoBRIPCgdIcFJhdGlvGAQgASgJEhAK",
            "CEF0a1JhdGlvGAUgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.ConfigLoreEntryQualityUnit), global::Config.ConfigLoreEntryQualityUnit.Parser, new[]{ "Id", "Quality", "Rate", "HpRatio", "AtkRatio" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigLoreEntryQualityUnit : pb::IMessage<ConfigLoreEntryQualityUnit> {
    private static readonly pb::MessageParser<ConfigLoreEntryQualityUnit> _parser = new pb::MessageParser<ConfigLoreEntryQualityUnit>(() => new ConfigLoreEntryQualityUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigLoreEntryQualityUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigLoreEntryQualityUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigLoreEntryQualityUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigLoreEntryQualityUnit(ConfigLoreEntryQualityUnit other) : this() {
      id_ = other.id_;
      quality_ = other.quality_;
      rate_ = other.rate_;
      hpRatio_ = other.hpRatio_;
      atkRatio_ = other.atkRatio_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigLoreEntryQualityUnit Clone() {
      return new ConfigLoreEntryQualityUnit(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Quality" field.</summary>
    public const int QualityFieldNumber = 2;
    private int quality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "Rate" field.</summary>
    public const int RateFieldNumber = 3;
    private int rate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "HpRatio" field.</summary>
    public const int HpRatioFieldNumber = 4;
    private string hpRatio_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HpRatio {
      get { return hpRatio_; }
      set {
        hpRatio_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AtkRatio" field.</summary>
    public const int AtkRatioFieldNumber = 5;
    private string atkRatio_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AtkRatio {
      get { return atkRatio_; }
      set {
        atkRatio_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigLoreEntryQualityUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigLoreEntryQualityUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Quality != other.Quality) return false;
      if (Rate != other.Rate) return false;
      if (HpRatio != other.HpRatio) return false;
      if (AtkRatio != other.AtkRatio) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Quality != 0) hash ^= Quality.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (HpRatio.Length != 0) hash ^= HpRatio.GetHashCode();
      if (AtkRatio.Length != 0) hash ^= AtkRatio.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Quality != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quality);
      }
      if (Rate != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rate);
      }
      if (HpRatio.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HpRatio);
      }
      if (AtkRatio.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AtkRatio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (HpRatio.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HpRatio);
      }
      if (AtkRatio.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AtkRatio);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigLoreEntryQualityUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Quality != 0) {
        Quality = other.Quality;
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      if (other.HpRatio.Length != 0) {
        HpRatio = other.HpRatio;
      }
      if (other.AtkRatio.Length != 0) {
        AtkRatio = other.AtkRatio;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Quality = input.ReadInt32();
            break;
          }
          case 24: {
            Rate = input.ReadInt32();
            break;
          }
          case 34: {
            HpRatio = input.ReadString();
            break;
          }
          case 42: {
            AtkRatio = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
