syntax = "proto2";
import "ErrCode.proto";
import "Enum.proto";
import "Common.proto";
package msg;

// 客户端ping
message ClientPing_CS 
{			//[default = eMsg_ClientPing_CS];		
}

// 客户端ping服务器回复
message ClientPing_SC 
{			//[default = eMsg_ClientPing_SC];
	optional uint64 time_stamp = 1;		//服务器时间戳
}

// 客户端发送PM命令
message Pm_CS 
{					//[default = eMsg_Pm_CS]
	optional string str_param = 1;		//PM命令
}

// 服务器端返回PM命令校验结果
message Pm_SC
{					//[default = eMsg_Pm_SC]
	optional string str_param = 1;		//PM命令
	optional eErrCode	result = 2;// [default = eSucceed];	
	optional uint64 server_time_stamp = 3;		//服务器时间戳
	optional uint64 server_daily_reset_time_stamp = 4;		//下一次每日重置服务器时间戳(目前都是服务器的0点)
}


//    登录后下发天赋
message PlayerTalents4Login_PC {			//[eMsg_PlayerTalents4Login_PC = 289;        ]
	repeated TalentInfo talents = 1;
	optional SplitPkgPC split_info = 2;
}

//eMsg_LoginFinish_SC 消息后，主动下发玩家基本信息
message PlayerBasicInfo4Login_PC {			//[default = eMsg_PlayerBasicInfo4Login_PC]
	optional uint64 user_id = 1;				//玩家id
	optional string name = 2;				//玩家名字	
	repeated PlayerAttr player_attr = 3;    //数值型属性组
	repeated PlayerEquipSlotsInfo equip_slots = 4;  //装备栏
	repeated PlayerRuneSlotsInfo rune_slots = 5;  //符石栏
	repeated PlayerPetSlotsInfo pet_slots = 6;  //宠物栏
	repeated PlayerSkillSlotsInfo skill_slots = 7;  //技能栏
	optional uint64 server_time_stamp = 8;		//服务器时间戳
	optional uint64 server_daily_reset_time_stamp = 9;		//下一次每日重置服务器时间戳(目前都是服务器的0点)
	optional uint64 server_weekly_reset_time_stamp = 10;		//下一次每周重置服务器时间戳(目前都是服务器的周一0点，一周的开始)
	repeated PlayerEquipSlotsInfo lore_equip_slots = 11;  //传承装备栏
	repeated PlayerHolySlotsInfo holy_slots = 12;  //圣物栏
}


//eMsg_LoginFinish_SC 消息后，//登录的章节地图和随机任务信息
message PlayerChapterMapInfo4Login_PC {			//[default = eMsg_PlayerChapterMapInfo4Login_PC = 287; ]
	optional ChapterMapInfo chapter_stage = 1;				//章节关卡信息
	repeated  RandomEvent events = 2;				//随机事件
	repeated FinishEvent  finshed_event_info = 3;  //完成随机事件信息
}

//eMsg_LoginFinish_SC 消息后，下发委托任务信息
message PlayerNPCTask4Login_PC {			//[default = eMsg_PlayerNPCTask4Login_PC = 288; ]
	repeated  NpcTask npc_tasks = 1;				//npc委托任务	
	repeated NpcTaskExchangeItemsInfo  exchange_info = 2; //兑换信息
}


// 客户端主动获取玩家信息
message PlayerInfo_CS {			//[default = eMsg_PlayerInfo_CS]
}

// 获取玩家信息反馈&&推送玩家信息
message PlayerInfo_SC {			//[default = eMsg_PlayerInfo_SC]
	optional uint64 user_id = 1;				//玩家id
	optional string name = 2;				//玩家名字	
	repeated PlayerAttr player_attr = 3;    //数值型属性组
	repeated PlayerEquipSlotsInfo equip_slots = 4;  //装备栏
	repeated PlayerRuneSlotsInfo rune_slots = 5;  //符石栏
	repeated PlayerPetSlotsInfo pet_slots = 6;  //宠物栏
	repeated PlayerSkillSlotsInfo skill_slots = 7;  //技能栏
}




    
	     

//升级基本属性
message RingAttrLevelUp_CS {	//[default = eMsg_RingAttrLevelUp_CS    =296; ]
	optional eBattleAttr attr_id = 1;   //要升级的属性id
	optional uint64 click_times = 2; //点击提交次数
}

//升级基本属性回复
message RingAttrLevelUp_SC {	//[default = eMsg_RingAttrLevelUp_SC    =297; ]
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional RingAttr ring_attr = 2;  //最新属性
	optional Finance finance = 3;  //最新账户余额
}
	

// 推送玩家属性更新
message PlayerInfoUpdate_PC {	//[default = eMsg_PlayerInfoUpdate_PC]
	repeated PlayerAttr player_attr = 1;
}

//传承装备栏更新  ---只下发变动的栏位，可能1个可能多个
message PlayerLoreEquipSlotUpdate_PC {	//[default = eMsg_PlayerLoreEquipSlotUpdate_PC = 290;]
	repeated PlayerEquipSlotsInfo equip_slots = 1;  //装备栏
}
//装备栏更新  ---只下发变动的栏位，可能1个可能多个
message PlayerEquipSlotUpdate_PC {	//[default = eMsg_PlayerEquipSlotUpdate_PC = 273;]
	repeated PlayerEquipSlotsInfo equip_slots = 1;  //装备栏
}
//符石栏更新 ---只下发变动的栏位，可能1个可能多个
message PlayerRuneSlotUpdate_PC {	//[default = eMsg_PlayerRuneSlotUpdate_PC = 276; ]
	repeated PlayerRuneSlotsInfo rune_slots = 1;  //符文栏
}
//宠物栏更新 ---只下发变动的栏位，可能1个可能多个
message PlayerPetSlotUpdate_PC {	//[default = eMsg_PlayerPetSlotUpdate_PC = 275;  ]
	repeated PlayerPetSlotsInfo pet_slots = 1;  //宠物栏
}
//英雄角色更新 ---只下发变动，可能1个可能多个
message PlayerHeroRoleUpdate_PC {	//[default = eMsg_PlayerHeroRoleUpdate_PC = 281;   ]
	repeated HeroRoleInfo heroes = 1;  //变更的英雄角色
}
//魔戒基本属性更新
message PlayerRingUpdate_PC {			//[eMsg_PlayerRingUpdate_PC    =273;     ]
	repeated RingAttr ring_attr = 1;
}
     
//技能栏更新  ---只下发变动的栏位，可能1个可能多个	
message PlayerSkillSlotUpdate_PC {			//[default = eMsg_PlayerSkillSlotUpdate_PC    =274;    ]
	repeated PlayerSkillSlotsInfo skill_slots = 1;
}

 
// 战斗各项属性发生变更 下发
message PlayerBattleAttrUpdate_PC {			//[eMsg_PlayerBattleAttrUpdate_PC= 283;     ]
	repeated BattleAttr battle_attr = 1;
	//repeated BattleBuff battle_buff = 2;             //时间结束才取消的buff  --废弃
	//repeated BattleBuff4Stage battle_buf_4stage = 3;  //关卡内有效的buff -- 废弃 专门有buff的 更新数据包
}

	

// 推送玩家升级(此处只做升级客户端表现，具体数值走PlayerInfoUpdate_PC协议)
message PlayerLvUp_PC {		//eMsg_PlayerLvUp_PC			= 342;
	optional uint32 target_lv = 1;
}

// 在线每日重置请求
message DailyReset_CS  { //eMsg_DailyReset_CS       = 315;      

}

// 在线每日重置请求反馈
message DailyReset_SC { //eMsg_DailyReset_SC       = 316;      
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional uint64 server_time_stamp = 2;		//服务器时间戳
	optional uint64 server_daily_reset_time_stamp = 3;		//下一次每日重置服务器时间戳(目前都是服务器的0点)
	optional uint64 server_weekly_reset_time_stamp = 4;		//下一次每周重置服务器时间戳(目前都是服务器的周一0点，一周的开始)
}
	


// 获取当前红点列表
message GetRedPoints_CS { //eMsg_GetRedPoints_CS		= 310;		
}

message RedPoint {
	optional eRedPointType type = 1;//红点类型
	optional int32 param = 2;		//红点参数，具体业务约定,详见枚举
}

// 获取当前红点列表反馈
message GetRedPoints_SC { //eMsg_GetRedPoints_SC		= 311;		
	repeated RedPoint red_points = 1;
}

// 主动推送红点下发 --- 登录或游戏中不是一定会有的，只有服务器端发现有设计需要通知的红点才会主动下发这个包
message SyncRedPoints_PC { //eMsg_SyncRedPoints_PC		= 312;		
	repeated RedPoint red_points = 1;
}



// 已读红点提交
message ReadRedPoints_CS { //eMsg_ReadRedPoints_CS       = 313;	
	optional RedPoint red_points = 1;
}

 // 已读红点提交反馈
message ReadRedPoints_SC { //eMsg_ReadRedPoints_SC       = 314; 
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional RedPoint red_points = 2;
}
      
	    


// 英雄转职 client-->server
message PlayerChangeHero_CS   //eMsg_PlayerChangeHero_CS    = 306;  
{
	optional int32 target_hero_id = 1;  // 转职目标英雄
	optional bool is_reset = 2; //是否重置  ，true重置，服务器会忽略target_hero_id，初始化英雄id
}


	     
// 英雄转职 client<--server
message PlayerChangeHero_SC   //eMsg_PlayerChangeHero_SC    = 307;  
{

	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional int32 hero_id = 2;  // 转职目标英雄
	optional Finance finance = 3; //最新账户货币信息,各种货币余额
	optional bool is_reset = 4; //本次操作是否重置
}

   

//eMsg_LoginFinish_SC 消息后，主动下发玩家英雄角色基本信息
message PlayerHeroRolesInfo4Login_PC {			//[eMsg_PlayerHeroRolesInfo4Login_PC    =280;     ]
	repeated HeroRoleInfo heroes = 1;
	optional SplitPkgPC split_info = 2;
}

//eMsg_LoginFinish_SC 消息后，主动下发魔戒属性基本信息
message PlayerRingInfo4Login_PC {			//[eMsg_PlayerRingInfo4Login_PC    =266;   ]
	repeated RingAttr ring_attr = 1;
}

//eMsg_LoginFinish_SC 消息后，主动下发魔戒属性基本信息
message PlayerRunesInfo4Login_PC {			//[eMsg_PlayerRunesInfo4Login_PC    =268;   ]
	repeated RuneInfo runes = 1;
	optional SplitPkgPC split_info = 2;
}
//eMsg_LoginFinish_SC 消息后，主动下发玩家传承装备基本信息
message PlayerLoreEquipsInfo4Login_PC {			//[default = eMsg_PlayerLoreEquipsInfo4Login_PC    =291]
	repeated EquipInfo equips = 1;
	optional SplitPkgPC split_info = 2;
}

//eMsg_LoginFinish_SC 消息后，主动下发玩家装备基本信息
message PlayerEquipsInfo4Login_PC {			//[default = eMsg_PlayerEquipsInfo4Login_PC    =267]
	repeated EquipInfo equips = 1;
	optional SplitPkgPC split_info = 2;
}
//eMsg_LoginFinish_SC 消息后，主动下发玩家宠物基本信息
message PlayerPetsInfo4Login_PC {			//[default = eMsg_PlayerPetsInfo4Login_PC    =269]

	repeated PetInfo pets = 1;
	optional SplitPkgPC split_info = 2;
}
//eMsg_LoginFinish_SC 消息后，主动下发圣物信息
message PlayerHolyItemsInfo4Login_PC {			//[default = eMsg_PlayerHolyItemsInfo4Login_PC = 292; //]
	repeated HolyItemInfo holy_items = 1;
	optional SplitPkgPC split_info = 2;
}

	


//eMsg_LoginFinish_SC 消息后，主动下发玩家道具基本信息
message PlayerItemsInfo4Login_PC {			//[default = eMsg_PlayerItemsInfo4Login_PC    =270]

	repeated ItemInfo items = 1;           //道具数
	optional SplitPkgPC split_info = 3;
}

//eMsg_LoginFinish_SC 消息后，主动下发玩家任务基本信息
message PlayerTaskInfo4Login_PC {			//[default = eMsg_PlayerTaskInfo4Login_PC    =271]

	optional uint32  main_task_id = 1 ;  //当前承接的主线任务id， 为0表示没有或都做完了
	optional int64  main_task_process = 2 ;  //当前承接的主线任务id对应的进度

}

//  eMsg_LoginFinish_SC 消息后，主动下发战斗总属性 (所有各项需要的属性)
message PlayerBattleAttrInfo4Login_PC {			//[eMsg_PlayerBattleAttrInfo4Login_PC = 282;     ]
	repeated BattleAttr battle_attr = 1;
	repeated BattleBuff battle_buff = 2;       //时间结束才取消的buff
	repeated BattleBuff4Stage battle_buf_4stage = 3;  //关卡内有效的buff
}
    
//eMsg_LoginFinish_SC 消息后，主动下发玩家技能基本信息
message PlayerSkillInfo4Login_PC {			//[default = eMsg_PlayerSkillInfo4Login_PC    =272; ]

	repeated SkillInfo skills = 1;
	optional SplitPkgPC split_info = 2;
}

       
//当前角色对应职业解锁新典籍
message PlayerUnlockNewClassics_PC {			//[eMsg_PlayerUnlockNewClassics_PC = 286;     ]
	optional OccupationClassic classics = 1;
}


//eMsg_LoginFinish_SC 消息后，主动下发玩家英雄角色对应的典籍信息
message PlayerOccupation2Classics4Login_PC {			//[eMsg_PlayerOccupation2Classics4Login_PC    =284;     ]
	repeated OccupationClassic classics = 1;
	optional SplitPkgPC split_info = 2;
}

	  
//典籍更新 ---只下发英雄变动引发职业变动，下发新角色的对应典籍
message PlayerOccupation2ClassicsUpdate_PC {			//[eMsg_PlayerOccupation2ClassicsUpdate_PC = 285;     ]
	repeated OccupationClassic classics = 1;
}

//升级典籍
message ClassicsLevelUp_CS { //eMsg_ClassicsLevelUp_CS    =294;
	optional int32 classic_id = 1;  //典籍ID
	optional int32 levels = 2;  //要升的等级数， 为0或为1则默认升1级。 大于1则表示升多个等级，服务器根据实际资源升具体的等级数
}

//升级典籍回复
message ClassicsLevelUp_SC { //eMsg_ClassicsLevelUp_SC    =295;     
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional OccupationClassic classic = 2;  //典籍最新信息
	optional Finance finance = 3;  //最新账户余额
	optional int32 final_levelups = 4; //本次的真实升级次数
}


 //英雄主技能升级请求
message HeroSkillLevelUp_CS  { //eMsg_HeroSkillLevelUp_CS = 340;    
    optional uint32 hero_id = 1; //英雄id
    optional uint32 level_up_values = 2; //升级数
}

//英雄主技能升级反馈
message HeroSkillLevelUp_SC{ //eMsg_HeroSkillLevelUp_SC = 341;      
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
    optional uint32 hero_id = 2; //英雄id
    optional uint32 skill_level = 3; //最新主技能等级
	optional Finance finance = 4;  //最新账户余额
	repeated ItemInfo items = 5;           //消耗道具 -- 显示外加本地数量扣除
	optional uint64  main_skill_damage = 6; //技能伤害
}
	   
	 
	 
	   
	
//神器升级请求
message ArtifactLevelUp_CS  { //eMsg_ArtifactLevelUp_CS = 1403;  
    optional ePlayerAttrID attr_id = 1; //神器枚举id
    optional uint32 level_up_values = 2; //升级数
}

//神器升级回复
message ArtifactLevelUp_SC{ //eMsg_ArtifactLevelUp_SC = 1404;
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
    optional ePlayerAttrID attr_id = 2; //神器枚举id
    optional uint32 levels = 3; //最新等级
	optional Finance finance = 4;  //最新账户余额
	repeated ItemInfo items = 5;           //消耗道具 -- 显示外加本地数量扣除
}


//eMsg_LoginFinish_SC 消息后，主动下发玩家宠物装备基本信息
//message PlayerPetEquipsInfo4Login_PC   //eMsg_PlayerPetEquipsInfo4Login_PC = 273;  
//{
//	repeated pet_equip  pet_equips = 1;
//	optional SplitPkgPC split_info = 3;
//}


    

//eMsg_LoginFinish_SC 消息后，主动下发玩家删除了的宠物(已拥有过但是进化被删除了)
//message PlayerDelPetInfo4Login_PC   //eMsg_PlayerDelPetInfo4Login_PC    =274; 
//{
//	repeated uint32  pet_id = 1;  //已删除的pet id
//}


     

//eMsg_LoginFinish_SC 消息后，主动下发玩家已解锁功能
message PlayerUnlockFunction4Login_PC   //eMsg_PlayerUnlockFunction4Login_PC    =278; 
{
	repeated FunctionInfo  unlock_functions = 1;  //已解锁功能
}

//eMsg_LoginFinish_SC 消息后，主动下发家园训练场技能
//message PlayerHomeTownTalent4Login_PC   //eMsg_PlayerHomeTownTalent4Login_PC    =279; 
//{
//	repeated TrainingTalentInfo  hometown_talent = 1;  //已解锁家园训练场技能
//}


	    
//eMsg_LoginFinish_SC 消息后，主动下发已完成的引导id
message PlayerGuideID4Login_PC   //eMsg_PlayerGuideID4Login_PC    =279; 
{
	repeated int32  guide_id = 1;  //已完成的引导id
}
	
	


//提交完成的引导id
message FinishedGuideID_CS   //eMsg_FinishedGuideID_CS    =298;
{
	repeated int32  guide_id = 1;  //提交的引导id
	optional bool is_hardcore = 2; //客户端要的标志位 
}

	
//回复服务器端保存完成的引导id
message FinishedGuideID_SC    //eMsg_FinishedGuideID_SC    =299; 
{
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	repeated int32  guide_id = 2;  //提交的引导id
	optional bool is_hardcore = 3; //客户端要的标志位 
}
	    
     

// 服务端：统计在线时长截止时间到数据刷新
message RefreshStatsOnLineTime_SC {            //[default = eMsg_RefreshStatsOnLineTime_SC]
}



// 获取玩家统计数据(关卡选择、成就达成等百分比)
message GetStatistics_CS {	//[default = eMsg_GetStatistics_CS]
	optional eStatisticType type = 1;
	repeated uint32 params = 2;			//请求参数列表
}

// 获取玩家统计数据反馈
message GetStatistics_SC {	//[default = eMsg_GetStatistics_SC]
	optional eStatisticType type = 1;
	repeated uint32 params = 2;			//请求参数列表
	repeated uint32 values = 3;			//请求参数列表对应百分比反馈
	optional uint32 nGateId = 4;					//服务端用
}

// 推送即将踢出客户端协议
message KickPlayer_SC { //eMsg_KickPlayer_SC			= 208;
	optional eKickReason reason = 1;	// 踢出原因
}



// 请求改名
message ChangePlayerName_CS//[default = eMsg_ChangePlayerName_CS];
{
	optional string	change_name = 1;		// 要改的名字
}

// 请求改名反馈
message ChangePlayerName_SC//[default = eMsg_ChangePlayerName_SC];
{
	optional string	change_name = 1;		// 要改的名字
	optional eErrCode	result = 2;// [default = eSucceed];	
	optional uint32	change_counter = 3;		// 最新修改名字次数
	optional Finance finance = 4; //最新账户货币信息,各种货币余额
}

// 检查是否重名请求
message CheckPlayerName_CS//[default = eMsg_CheckPlayerName_CS 		= 3104];
{
	optional string	new_name = 1;		// 要改的名字
}

// 检查是否重名回复
message CheckPlayerName_SC//[default = eMsg_CheckPlayerName_SC 		= 3105];
{
	optional string	new_name = 1;		// 要改的名字
	optional eErrCode result = 2;		// 错误码
}


// 隔日数据重置通知
message NewDayReset_PC {	//eMsg_NewDayReset_PC			= 338;	
	optional uint64 time_stamp = 1;			//当前时间戳
	optional uint64 next_reset_time_stamp = 2;			//下一次每日重置时间戳
	optional uint64 server_daily_reset_time_stamp = 3;		//下一次每日重置服务器时间戳(目前都是服务器的0点)
	optional uint64 server_weekly_reset_time_stamp = 4;		//下一次每周重置服务器时间戳(目前都是服务器的周一0点，一周的开始)
}

	




// 获取屏蔽词库列表
message GetForbiddenWord_CS {		// eMsg_GetForbiddenWord_CS
	optional uint32 clientversion = 1;		// 客户端屏蔽词库版本号
	optional uint64 lastid = 2;				// 上个包最后的id，0-重头开始取
}

// 屏蔽词库条目
message ForbiddenWord {
	optional uint64 guid = 1;				// id
	optional string forbiddenword = 2;		// 屏蔽词内容
	optional uint32 type = 3;				// 屏蔽类型：0=模糊，1=精确
}

// 获取屏蔽词库列表反馈
message GetForbiddenWord_SC {		// eMsg_GetForbiddenWord_SC
	optional uint32 serverversion = 1;		// 服务端屏蔽词库版本号，如果跟客户端版本号一样，则不下发列表
	repeated ForbiddenWord words = 2;		// 屏蔽词库列表
	optional uint32 endflag = 3;			// 结束标志：1-最后一个包
	optional eErrCode err_code = 4;			// 错误码
}


	     
	     
	     
	    
	     
	   

// 角色使用道具提升经验请求
message HeroAddExp_CS   //eMsg_HeroAddExp_CS       = 317; 
{
	optional uint32 hero_id = 1; //英雄角色 配置表里的 id
	repeated ItemInfo used_items = 2; //使用的升级道具
}	                
	
//角色使用道具提升经验反馈
message HeroAddExp_SC    //eMsg_HeroAddExp_SC       = 318; 
{
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional HeroRoleInfo  hero_info = 2;  //最新英雄信息
	repeated ItemInfo cost_items = 3; //被使用掉的道具信息
}

// 角色使用道具突破请求
message HeroBreak_CS   //eMsg_HeroBreak_CS       = 319; 
{
	optional uint32 hero_id = 1; //英雄角色 配置表里的 id
	repeated ItemInfo used_items = 2; //使用的升级道具
}	                
	
// 角色使用道具突破反馈
message HeroBreak_SC    //eMsg_HeroBreak_SC       = 320;  
{
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional HeroRoleInfo  hero_info = 2;  //最新英雄信息
	repeated ItemInfo cost_items = 3; //被使用掉的道具信息
}


// 角色上阵切换请求
message HeroReplaceInBattle_CS   //eMsg_HeroReplaceInBattle_CS       = 321; 
{
	optional uint32 hero_id = 1; //将要提交上阵的英雄角色id
}	                
	
// 角色上阵切换反馈
message HeroReplaceInBattle_SC    //eMsg_HeroReplaceInBattle_SC       = 322;   
{
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional uint32 hero_id = 2; //最新上阵英雄角色id
	optional uint32 out_battle_hero_id = 3; //替换下场的英雄角色id
}

 // 角色碎片合成请求
message HeroPiecesMerge_CS   //eMsg_HeroPiecesMerge_CS       = 323;
{
	optional uint32 hero_id = 1; //要合成的英雄id
}	                
	
 // 角色碎片合成反馈
message HeroPiecesMerge_SC    //eMsg_HeroPiecesMerge_SC       = 324; 
{
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional HeroRoleInfo  hero_info = 2;  //合成成功的话，下发的最新英雄信息
	repeated ItemInfo cost_items = 3; //被使用掉的道具信息--扣除的碎片信息
}

// 新增角色英雄下发 --运营补偿或作弊码  
message NewHero_PC     //eMsg_NewHero_PC       = 325; 
{
	repeated HeroRoleInfo  hero_info = 1;  //下发的最新英雄信息
}


	     
	          
	    
// 看广告获得经验药水
message HeroExpItemByFreeAD_CS   //eMsg_HeroExpItemByFreeAD_CS       = 326; 
{
}	                
	
// 看广告获得经验药水反馈	   
message HeroExpItemByFreeAD_SC    //eMsg_HeroExpItemByFreeAD_SC       = 327;
{
	optional eErrCode	result = 1;// [default = eSucceed];	 //处理结果
	optional uint32  remain_free_times = 2;  //剩余免费广告次数
	repeated ItemInfo award_items = 3; //获得的奖励物品
}                

